//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Svam.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class acc_tallyexports
    {
        public int ID { get; set; }
        public string VoucherNumber { get; set; }
        public string VoucherType { get; set; }
        public Nullable<int> CompanyID { get; set; }
        public Nullable<int> BranchCode { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public string flag { get; set; }
        public string SyncID { get; set; }
    }
}
