//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Svam.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class acc_journalvouchers
    {
        public int ID { get; set; }
        public System.DateTime JournalVoucherDate { get; set; }
        public System.DateTime AccountingDate { get; set; }
        public string Remarks { get; set; }
        public string Status { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public string ReferenceNo { get; set; }
        public Nullable<System.DateTime> ReferenceDate { get; set; }
        public int BranchCode { get; set; }
        public Nullable<int> Document { get; set; }
        public string JournalVoucherNo { get; set; }
        public Nullable<int> CompanyID { get; set; }
        public string EntryType { get; set; }
        public string flag { get; set; }
        public string SyncID { get; set; }
        public string SystemVoucherNo { get; set; }
    }
}
