//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Svam.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class acc_generalledger
    {
        public int ID { get; set; }
        public System.DateTime AccountingDate { get; set; }
        public string TransactionTypeCode { get; set; }
        public string VoucherNo { get; set; }
        public System.DateTime VoucherDate { get; set; }
        public int AccountNumber { get; set; }
        public string AmountAttribute { get; set; }
        public Nullable<decimal> Dr { get; set; }
        public Nullable<decimal> Cr { get; set; }
        public string Particulars { get; set; }
        public string Reconciled { get; set; }
        public string Remarks { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public Nullable<int> BranchCode { get; set; }
        public int GeneralLedgerLineID { get; set; }
        public Nullable<int> ChequeID { get; set; }
        public string SLGroupCode { get; set; }
        public string SubLedger { get; set; }
        public string SyncID { get; set; }
        public string flag { get; set; }
    }
}
