//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Svam.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class acc_bankstatements
    {
        public int ID { get; set; }
        public string BankAccountNo { get; set; }
        public System.DateTime AccountingDate { get; set; }
        public string Particulars { get; set; }
        public string ChequeNo { get; set; }
        public Nullable<decimal> Dr { get; set; }
        public Nullable<decimal> Cr { get; set; }
        public Nullable<decimal> Balance { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public int BranchCode { get; set; }
        public int BankStatementsLineID { get; set; }
        public string SyncID { get; set; }
        public string flag { get; set; }
    }
}
