//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Svam.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class acc_bankaccounts
    {
        public string BankAccountNo { get; set; }
        public int BankID { get; set; }
        public string BranchName { get; set; }
        public string BranchAddress { get; set; }
        public string PhoneNo { get; set; }
        public int AccountNumber { get; set; }
        public string Particulars { get; set; }
        public string Default { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public int BranchCode { get; set; }
        public string BankAccountName { get; set; }
        public string NEFTCode { get; set; }
        public string SyncID { get; set; }
        public string flag { get; set; }
    }
}
