//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Svam.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class acc_countries
    {
        public int id { get; set; }
        public string country_name { get; set; }
        public string country_code { get; set; }
        public string dial_code { get; set; }
        public string currency_name { get; set; }
        public string currency_symbol { get; set; }
        public string currency_code { get; set; }
        public Nullable<int> CompanyID { get; set; }
        public Nullable<int> BranchCode { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<int> mastercompany { get; set; }
        public string SyncID { get; set; }
        public string flag { get; set; }
    }
}
