//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Svam.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class addto_wishlist
    {
        public int id { get; set; }
        public string pid { get; set; }
        public int price { get; set; }
        public string createdBy { get; set; }
        public System.DateTime createdDate { get; set; }
        public int company_id { get; set; }
        public int branch { get; set; }
        public string flag { get; set; }
        public string SyncID { get; set; }
        public int userID { get; set; }
    }
}
