//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Svam.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class all_custom_menu
    {
        public int id { get; set; }
        public string menuId { get; set; }
        public string menuName { get; set; }
        public string companyId { get; set; }
        public string branchCode { get; set; }
        public string createdBy { get; set; }
        public System.DateTime createdDate { get; set; }
        public string modifiedBy { get; set; }
        public string modifiedDate { get; set; }
        public string flag { get; set; }
        public string syncId { get; set; }
        public string Status { get; set; }
    }
}
