//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Svam.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class all_menu13march21
    {
        public int Menu_Id { get; set; }
        public string Menu_Name { get; set; }
        public int ParentId { get; set; }
        public string Menu_Url { get; set; }
        public string SubMenu { get; set; }
        public Nullable<int> Orderby { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public Nullable<int> BranchCode { get; set; }
        public string CreatedBy { get; set; }
        public string ModifiedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string IsActive { get; set; }
        public string Menu_Name2 { get; set; }
        public string SyncID { get; set; }
        public string flag { get; set; }
    }
}
