//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Svam.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class allocate
    {
        public long id { get; set; }
        public string machine { get; set; }
        public string site_name { get; set; }
        public Nullable<decimal> daily_rent { get; set; }
        public Nullable<decimal> monthly_rent { get; set; }
        public Nullable<int> quantity { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> CompanyID { get; set; }
        public Nullable<int> BranchCode { get; set; }
        public string Flag { get; set; }
        public string SyncID { get; set; }
    }
}
