//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Svam.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ast_assetmaintenance
    {
        public int ID { get; set; }
        public string AssetNo { get; set; }
        public System.DateTime MaintenanceDate { get; set; }
        public string MaintenanceBy { get; set; }
        public decimal MaintenanceCost { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> NextScheduleMaintenance { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public int BranchCode { get; set; }
        public Nullable<int> Document { get; set; }
        public string SyncID { get; set; }
        public string flag { get; set; }
    }
}
