//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Svam.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class bank_master
    {
        public int id { get; set; }
        public string BankCode { get; set; }
        public string BankName { get; set; }
        public string BranchCode { get; set; }
        public string Ifsccode { get; set; }
        public string othercode { get; set; }
        public string Address { get; set; }
        public string Phno { get; set; }
        public string mailId { get; set; }
        public string ContactPer1 { get; set; }
        public string ContactPer2 { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string SyncID { get; set; }
        public string flag { get; set; }
    }
}
