//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Svam.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class barcodesetting
    {
        public int ID { get; set; }
        public string CompanyName { get; set; }
        public string ItemName { get; set; }
        public string MRP { get; set; }
        public string OurPrice { get; set; }
        public string IsSize { get; set; }
        public string IsColor { get; set; }
        public Nullable<int> CompanyID { get; set; }
        public Nullable<int> BranchCode { get; set; }
        public string flag { get; set; }
        public string SyncId { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string PackingDate { get; set; }
        public string ExpiryDate { get; set; }
        public string CustomText { get; set; }
    }
}
