//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Svam.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class cashbankbook
    {
        public int id { get; set; }
        public string partyid { get; set; }
        public string EntryNo { get; set; }
        public string partyname { get; set; }
        public System.DateTime entrydate { get; set; }
        public string paymentmode { get; set; }
        public string chequeno { get; set; }
        public string chequedate { get; set; }
        public string bankname { get; set; }
        public string narration { get; set; }
        public decimal Pbalance { get; set; }
        public decimal amountpaid { get; set; }
        public decimal currentbalance { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string CompanyId { get; set; }
        public string BranchCode { get; set; }
        public string flag { get; set; }
        public string SyncID { get; set; }
    }
}
