//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Svam.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class challanamst
    {
        public int id { get; set; }
        public Nullable<int> customers_ID { get; set; }
        public string ChalanNo { get; set; }
        public Nullable<System.DateTime> ChalanDt { get; set; }
        public string CustoNm { get; set; }
        public string MobileNo { get; set; }
        public string Address { get; set; }
        public Nullable<System.DateTime> DueDt { get; set; }
        public string Rmk { get; set; }
        public string Shift { get; set; }
        public Nullable<decimal> Total { get; set; }
        public Nullable<decimal> DisPer { get; set; }
        public Nullable<decimal> DisAmt { get; set; }
        public Nullable<decimal> GrandTotal { get; set; }
        public string PaymentMode { get; set; }
        public Nullable<decimal> Receivableamt { get; set; }
        public Nullable<decimal> BalanceAmt { get; set; }
        public string Trasport { get; set; }
        public string RefNo { get; set; }
        public Nullable<System.DateTime> RefDt { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public int CustID { get; set; }
        public Nullable<int> branch { get; set; }
        public string CompanyID { get; set; }
        public string SaleRefNo { get; set; }
        public string SaleRefDate { get; set; }
        public string SaleDelieveryPlace { get; set; }
        public string SalePaymentMode { get; set; }
        public string ChequeNo { get; set; }
        public string NameOnCard { get; set; }
        public string CardNumber { get; set; }
        public string BankName { get; set; }
        public Nullable<float> PayAmount { get; set; }
        public string SaleRemarks { get; set; }
        public string CardName { get; set; }
        public string CardNo { get; set; }
        public Nullable<decimal> RefundAmount { get; set; }
        public Nullable<decimal> WalletDeduction { get; set; }
        public string InvoiceStatus { get; set; }
        public string Status { get; set; }
        public string file { get; set; }
        public string OnlineOrderStatus { get; set; }
        public string challanamstcolumn1 { get; set; }
        public string challanamstcolumn { get; set; }
        public string challanamstcolumn3 { get; set; }
        public string challanamstcolumn4 { get; set; }
        public string challanamstcolumn5 { get; set; }
        public Nullable<decimal> challanamstcolumn6 { get; set; }
        public Nullable<decimal> challanamstcolumn7 { get; set; }
        public Nullable<decimal> challanamstcolumn8 { get; set; }
        public Nullable<decimal> challanamstcolumn9 { get; set; }
        public Nullable<decimal> challanamstcolumn10 { get; set; }
        public string HoldType { get; set; }
        public string flag { get; set; }
        public string SyncID { get; set; }
        public string SystemVoucherNo { get; set; }
        public string pincode { get; set; }
        public string AddressID { get; set; }
        public string SalesPersonID { get; set; }
        public string Additional1 { get; set; }
        public string Additional2 { get; set; }
        public string Additional3 { get; set; }
        public string Additional4 { get; set; }
        public string Additional5 { get; set; }
        public Nullable<float> TcsAmount { get; set; }
        public string EntryType { get; set; }
        public Nullable<decimal> TaxPer { get; set; }
        public string AditionalTax { get; set; }
        public Nullable<decimal> AditionalTaxAmt { get; set; }
        public string OnlineOrderNo { get; set; }
        public string bill_type { get; set; }
        public string sales_bill_type { get; set; }
        public Nullable<System.DateTime> start_date { get; set; }
        public Nullable<System.DateTime> end_date { get; set; }
        public Nullable<int> report_status { get; set; }
        public Nullable<decimal> packing_charges { get; set; }
        public Nullable<decimal> packing_charges_gst_per { get; set; }
        public Nullable<decimal> insurance_charges { get; set; }
        public Nullable<decimal> insurance_charges_gst_per { get; set; }
        public Nullable<decimal> forwarding_charges { get; set; }
        public Nullable<decimal> forwarding_charges_gst_per { get; set; }
        public Nullable<decimal> other_charges { get; set; }
        public Nullable<decimal> other_charges_gst_per { get; set; }
        public Nullable<decimal> Gsttotal { get; set; }
        public Nullable<decimal> freight_charges_gst_per { get; set; }
        public Nullable<decimal> Adjustment { get; set; }
        public Nullable<decimal> Receivedamt { get; set; }
    }
}
