//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Svam.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class chalandetblack
    {
        public int id { get; set; }
        public Nullable<int> inv_itemsku_ID { get; set; }
        public Nullable<int> challanamst_id { get; set; }
        public string Chalanno { get; set; }
        public Nullable<System.DateTime> ChalanDt { get; set; }
        public string Particular { get; set; }
        public Nullable<decimal> Qty { get; set; }
        public Nullable<decimal> Rate { get; set; }
        public string Unit { get; set; }
        public Nullable<decimal> Amt { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string size { get; set; }
        public string itmcode { get; set; }
        public string catID { get; set; }
        public Nullable<decimal> disper { get; set; }
        public Nullable<decimal> disamnt { get; set; }
        public Nullable<decimal> finalamnt { get; set; }
        public Nullable<decimal> newprice { get; set; }
        public Nullable<decimal> gstper { get; set; }
        public Nullable<decimal> gstamt { get; set; }
        public Nullable<int> branch { get; set; }
        public string CompanyID { get; set; }
        public decimal amountaftergst { get; set; }
        public string isactive { get; set; }
        public Nullable<decimal> ReturnQty { get; set; }
        public Nullable<decimal> CessPer { get; set; }
        public Nullable<decimal> CessAmount { get; set; }
        public string chalandetcolumn1 { get; set; }
        public string chalandetcolumn2 { get; set; }
        public string chalandetcolumn3 { get; set; }
        public string chalandetcolumn4 { get; set; }
        public string chalandetcolumn5 { get; set; }
        public Nullable<decimal> chalandetcolumn6 { get; set; }
        public Nullable<decimal> chalandetcolumn7 { get; set; }
        public Nullable<decimal> chalandetcolumn8 { get; set; }
        public Nullable<decimal> chalandetcolumn9 { get; set; }
        public Nullable<decimal> chalandetcolumn10 { get; set; }
        public string flag { get; set; }
        public string SyncID { get; set; }
    }
}
