//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Svam.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ci_session_temp
    {
        public string id { get; set; }
        public string ip_address { get; set; }
        public string timestamp { get; set; }
        public byte[] data { get; set; }
        public string dumpkey { get; set; }
        public string SyncID { get; set; }
        public string flag { get; set; }
    }
}
