//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Svam.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class com_organizations
    {
        public int ID { get; set; }
        public string Organization { get; set; }
        public Nullable<int> Logo { get; set; }
        public Nullable<int> EstablishmentYear { get; set; }
        public string Caption { get; set; }
        public string Website { get; set; }
        public string RegistrationNo { get; set; }
        public Nullable<int> ParentOrganizationID { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public int BranchCode { get; set; }
        public int OrganizationID { get; set; }
        public string SyncID { get; set; }
        public string flag { get; set; }
    }
}
