//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Svam.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class com_branches
    {
        public int OrganizationID { get; set; }
        public string BranchTypeCode { get; set; }
        public int OrgBranchCode { get; set; }
        public string BranchName { get; set; }
        public string Logo { get; set; }
        public string InvoiceType { get; set; }
        public string InvoiceFormat { get; set; }
        public Nullable<int> NoOfCopies { get; set; }
        public string TNC { get; set; }
        public string FreightCharges { get; set; }
        public Nullable<System.DateTime> FromDate { get; set; }
        public Nullable<System.DateTime> ToDate { get; set; }
        public string FileName { get; set; }
        public string FileExt { get; set; }
        public string FilePath { get; set; }
        public Nullable<int> ManagerID { get; set; }
        public Nullable<int> AsstManagerID { get; set; }
        public Nullable<decimal> Target { get; set; }
        public Nullable<int> Area { get; set; }
        public string Remarks { get; set; }
        public string StateId { get; set; }
        public string City { get; set; }
        public string Address { get; set; }
        public string CountryID { get; set; }
        public string EmailID { get; set; }
        public string Password { get; set; }
        public string MobileNo { get; set; }
        public string AltMob { get; set; }
        public string PhoneNo1 { get; set; }
        public string PhoneNo2 { get; set; }
        public string FaxNo { get; set; }
        public string TINNo { get; set; }
        public string CSTNo { get; set; }
        public string VATNo { get; set; }
        public string FranchiseNo { get; set; }
        public string ZipCode { get; set; }
        public string GoogleVerifiedAddress { get; set; }
        public string Latitude { get; set; }
        public string Longitude { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public int BranchCode { get; set; }
        public string Registered { get; set; }
        public string IsActive { get; set; }
        public string SubscriptionStatus { get; set; }
        public string OrderVisibilityStatus { get; set; }
        public Nullable<System.DateTime> SubscriptionStartDate { get; set; }
        public Nullable<System.DateTime> SubscriptionEndDate { get; set; }
        public string Website { get; set; }
        public string BankDetail { get; set; }
        public string flag { get; set; }
        public string SyncID { get; set; }
        public Nullable<int> mastercompany { get; set; }
        public string KeyVersion { get; set; }
    }
}
