//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Svam.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class company_profile
    {
        public int ID { get; set; }
        public string Organization { get; set; }
        public string Logo { get; set; }
        public string ecom_logo { get; set; }
        public string fab_icon { get; set; }
        public string EstablishmentYear { get; set; }
        public string Website { get; set; }
        public string Amazon_SellerId { get; set; }
        public string Amazon_AWSAccessKeyId { get; set; }
        public string Amazon_SecretKey { get; set; }
        public string Amazon_MarketPlaceId { get; set; }
        public string Amazon_MWSAuthToken { get; set; }
        public string FlipkartAffiliateId { get; set; }
        public string FlipkartAccessToken { get; set; }
        public string RegistrationNo { get; set; }
        public string Phoneno { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string Address { get; set; }
        public string Address2 { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string FileName { get; set; }
        public string FileExt { get; set; }
        public string FilePath { get; set; }
        public string InvoiceType { get; set; }
        public string ZipCode { get; set; }
        public string LocalityName { get; set; }
        public string GoogleVerifiedAddress { get; set; }
        public string Country { get; set; }
        public string State { get; set; }
        public string City { get; set; }
        public string TNC { get; set; }
        public int No_of_users { get; set; }
        public Nullable<int> No_of_users_soft { get; set; }
        public Nullable<int> no_of_admin_users { get; set; }
        public Nullable<int> no_of_leads { get; set; }
        public Nullable<int> no_of_invoices { get; set; }
        public Nullable<int> no_of_companies { get; set; }
        public Nullable<int> no_of_branches { get; set; }
        public string IsActive { get; set; }
        public string Bill_Formate { get; set; }
        public string AboutUs { get; set; }
        public string homePageContent { get; set; }
        public string PrivacyPolicy { get; set; }
        public string ReturnPolicy { get; set; }
        public string AltEmailAddress { get; set; }
        public string FacebookLink { get; set; }
        public string LinkedInLink { get; set; }
        public string TwitterLink { get; set; }
        public string FreightCharges { get; set; }
        public string TransportCharges { get; set; }
        public string OtherCharges { get; set; }
        public Nullable<System.DateTime> FromDate { get; set; }
        public Nullable<System.DateTime> ToDate { get; set; }
        public string flag { get; set; }
        public string productkey { get; set; }
        public string CPUID { get; set; }
        public string company_type { get; set; }
        public string BankDetail { get; set; }
        public string tax_rate { get; set; }
        public string keywords { get; set; }
        public string meta_tags { get; set; }
        public string services { get; set; }
        public string terms_condition { get; set; }
        public string SyncID { get; set; }
        public string title { get; set; }
        public string whatsapp_no { get; set; }
        public int w_status { get; set; }
        public string permissions { get; set; }
        public string app_version { get; set; }
        public string ecom_organization { get; set; }
        public string ecom_email { get; set; }
        public string alt_phoneno { get; set; }
        public Nullable<int> mastercompany { get; set; }
        public string currencyId { get; set; }
        public string timeZone { get; set; }
        public string dateFormat { get; set; }
        public string lang { get; set; }
        public string KeyVersion { get; set; }
        public string registerBy_code { get; set; }
        public string Status { get; set; }
        public string VATApply { get; set; }
        public string TCSApply { get; set; }
        public string PlayStoreLink { get; set; }
        public string IOSLink { get; set; }
    }
}
