//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Svam.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class createprintorder
    {
        public int id { get; set; }
        public Nullable<int> customers_ID { get; set; }
        public string ChalanNo { get; set; }
        public Nullable<System.DateTime> ChalanDt { get; set; }
        public string CustoNm { get; set; }
        public string MobileNo { get; set; }
        public string Address { get; set; }
        public Nullable<System.DateTime> DueDt { get; set; }
        public string Rmk { get; set; }
        public string Shift { get; set; }
        public Nullable<decimal> Total { get; set; }
        public Nullable<decimal> DisPer { get; set; }
        public Nullable<decimal> DisAmt { get; set; }
        public Nullable<decimal> GrandTotal { get; set; }
        public string PaymentMode { get; set; }
        public Nullable<decimal> Receivableamt { get; set; }
        public Nullable<decimal> BalanceAmt { get; set; }
        public string Trasport { get; set; }
        public string RefNo { get; set; }
        public Nullable<System.DateTime> RefDt { get; set; }
        public Nullable<decimal> Weight { get; set; }
        public string WeightUnit { get; set; }
        public Nullable<int> TotalQty { get; set; }
        public Nullable<int> SentQty { get; set; }
        public Nullable<int> RemQty { get; set; }
        public string Particular { get; set; }
        public string SKU { get; set; }
        public string Color { get; set; }
        public string Size { get; set; }
        public string Unit { get; set; }
        public Nullable<decimal> Ourprice { get; set; }
        public Nullable<System.DateTime> Delivery { get; set; }
        public Nullable<decimal> mrp { get; set; }
        public Nullable<decimal> gstper { get; set; }
        public Nullable<decimal> gstamt { get; set; }
        public Nullable<int> BranchCode { get; set; }
        public string CompanyID { get; set; }
        public string SaleRefNo { get; set; }
        public string SaleRefDate { get; set; }
        public string SaleDelieveryPlace { get; set; }
        public string SalePaymentMode { get; set; }
        public string ChequeNo { get; set; }
        public string NameOnCard { get; set; }
        public string CardNumber { get; set; }
        public string BankName { get; set; }
        public Nullable<float> PayAmount { get; set; }
        public string SaleRemarks { get; set; }
        public string SaleOrderNo { get; set; }
        public string CardName { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string CardNo { get; set; }
        public Nullable<decimal> RefundAmount { get; set; }
        public Nullable<decimal> WalletDeduction { get; set; }
        public string InvoiceStatus { get; set; }
        public string OnlineOrderStatus { get; set; }
        public string challanamstcolumn1 { get; set; }
        public string challanamstcolumn { get; set; }
        public string challanamstcolumn3 { get; set; }
        public string challanamstcolumn4 { get; set; }
        public string challanamstcolumn5 { get; set; }
        public Nullable<decimal> challanamstcolumn6 { get; set; }
        public Nullable<decimal> challanamstcolumn7 { get; set; }
        public Nullable<decimal> challanamstcolumn8 { get; set; }
        public Nullable<decimal> challanamstcolumn9 { get; set; }
        public Nullable<decimal> challanamstcolumn10 { get; set; }
        public string HoldType { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string flag { get; set; }
        public string SyncID { get; set; }
        public Nullable<decimal> totalamt { get; set; }
        public string CategoryID { get; set; }
        public Nullable<int> SubCatId { get; set; }
        public Nullable<int> SubSubCatId { get; set; }
        public Nullable<int> SubSubSubCatId { get; set; }
        public string CustomerID { get; set; }
    }
}
