//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Svam.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class crm_viewleadsetting
    {
        public int Id { get; set; }
        public int CompanyID { get; set; }
        public int BranchID { get; set; }
        public bool IsEmail { get; set; }
        public bool IsCity { get; set; }
        public bool IsAssignedBy { get; set; }
        public bool IsAssignTo { get; set; }
        public bool IsAssignedDate { get; set; }
        public bool IsExpClosingDate { get; set; }
        public bool IsExpDealAmount { get; set; }
        public bool IsActive { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public bool IsCreatedBy { get; set; }
        public bool IsCreatedDate { get; set; }
        public bool IsModifiedDate { get; set; }
        public string ReportTextName { get; set; }
        public string LeadSampleTextName { get; set; }
        public string FBLeadSampleTextName { get; set; }
        public string TotalLeadTextName { get; set; }
        public bool IsCountry { get; set; }
        public bool IsState { get; set; }
        public bool IsProductType { get; set; }
        public bool IsLeadResource { get; set; }
        public bool IsAddress { get; set; }
        public bool IsUrl { get; set; }
        public bool IsSkypeId { get; set; }
        public bool IsTimeZoneName { get; set; }
        public bool IsOrganization { get; set; }
        public bool IsExtraCol1 { get; set; }
        public bool IsExtraCol2 { get; set; }
        public bool IsExtraCol3 { get; set; }
        public bool IsExtraCol4 { get; set; }
        public bool IsExtraCol5 { get; set; }
        public bool IsExtraCol6 { get; set; }
        public bool IsExtraCol7 { get; set; }
        public bool IsExtraCol8 { get; set; }
        public bool IsExtraCol9 { get; set; }
        public bool IsExtraCol10 { get; set; }
        public bool IsDOB { get; set; }
        public bool IsMrgAnnivarsary { get; set; }
        public bool IsDesignation { get; set; }
        public bool IsExtraCol9Filter { get; set; }
        public bool IsExtraCol10Filter { get; set; }
        public bool IsTermFilter { get; set; }
        public bool IsProductTypeFilter { get; set; }
        public bool IsLeadSourceFilter { get; set; }
        public bool IsExtraCol11 { get; set; }
        public bool IsExtraCol12 { get; set; }
        public bool IsExtraCol13 { get; set; }
        public bool IsExtraCol14 { get; set; }
        public bool IsExtraCol15 { get; set; }
        public bool IsExtraCol16 { get; set; }
        public bool IsExtraCol17 { get; set; }
        public bool IsExtraCol18 { get; set; }
        public bool IsExtraCol19 { get; set; }
        public bool IsExtraCol20 { get; set; }
        public bool IsExtraCol18Filter { get; set; }
        public bool IsExtraCol19Filter { get; set; }
        public bool IsExtraCol20Filter { get; set; }
        public bool IsCustomerNameFilter { get; set; }
        public bool IsMobNoFilter { get; set; }
        public bool IsEmailFilter { get; set; }
        public bool IsDesigFilter { get; set; }
        public bool IsOrgNameFilter { get; set; }
        public bool IsSkypIdFilter { get; set; }
        public bool IsFollowUpTime { get; set; }
        public bool IsFollowUpTimeIST { get; set; }
        public bool IsExtraCol1dropdown { get; set; }
        public bool IsExtraCol2dropdown { get; set; }
        public bool IsExtraCol3dropdown { get; set; }
        public bool IsExtraCol4dropdown { get; set; }
        public bool IsExtraCol5dropdown { get; set; }
        public bool IsExtraCol1dropdownFilter { get; set; }
        public bool IsExtraCol2dropdownFilter { get; set; }
        public bool IsExtraCol3dropdownFilter { get; set; }
        public bool IsExtraCol4dropdownFilter { get; set; }
        public bool IsExtraCol5dropdownFilter { get; set; }
    }
}
