//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Svam.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class crm_emailsetting
    {
        public int EmailSettingID { get; set; }
        public string EmailAddress { get; set; }
        public string SMTPHost { get; set; }
        public Nullable<int> Port { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public Nullable<bool> SSL { get; set; }
        public string CCEmail { get; set; }
        public string DisplayName { get; set; }
        public Nullable<int> CompanyID { get; set; }
        public Nullable<int> BranchCode { get; set; }
        public string flag { get; set; }
        public string SyncID { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    }
}
