//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Svam.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class crm_salestarget
    {
        public int TargetID { get; set; }
        public Nullable<int> SalePersonID { get; set; }
        public Nullable<System.DateTime> FromDate { get; set; }
        public Nullable<System.DateTime> ToDate { get; set; }
        public Nullable<decimal> TargetAchieveAmount { get; set; }
        public Nullable<long> CompanyID { get; set; }
        public Nullable<long> BranchID { get; set; }
    }
}
