//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Svam.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class crm_roleassigntbl
    {
        public int Id { get; set; }
        public string ProfileName { get; set; }
        public Nullable<bool> CreateLeads { get; set; }
        public Nullable<bool> ViewLeads { get; set; }
        public Nullable<bool> ViewSales { get; set; }
        public Nullable<bool> AssignLeadManagement { get; set; }
        public Nullable<bool> DeveloperReport { get; set; }
        public Nullable<bool> CommonActivityRemark { get; set; }
        public Nullable<bool> RoleManagement { get; set; }
        public Nullable<bool> Notification { get; set; }
        public Nullable<bool> LeadNotify { get; set; }
        public Nullable<bool> ProjectManagement { get; set; }
        public Nullable<bool> LeadManagement { get; set; }
        public Nullable<bool> DailyWorkSchedule { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<int> BranchID { get; set; }
        public Nullable<int> CompanyID { get; set; }
        public Nullable<bool> Viewpayment { get; set; }
        public bool TicketManagement { get; set; }
        public bool NewLeave { get; set; }
        public bool ViewLeave { get; set; }
        public bool FileManager { get; set; }
        public bool TrackSalePerson { get; set; }
        public bool ViewMapSalePerson { get; set; }
        public bool AddQuotation { get; set; }
        public bool CreateAssignWork { get; set; }
        public bool ViewAssignedWorks { get; set; }
        public bool LeaveManagement { get; set; }
        public bool EmpAttendence { get; set; }
        public bool EmpLoginHistory { get; set; }
        public bool ManualAttandence { get; set; }
        public bool ManageSalary { get; set; }
        public bool ManageExtraPayment { get; set; }
        public bool EmpLeaveRequest { get; set; }
        public bool CreateInterviewSchedule { get; set; }
        public bool ViewInterviewSchedule { get; set; }
        public bool ManageUser { get; set; }
        public bool CreateTicket { get; set; }
        public bool ViewTicket { get; set; }
        public bool MappedUser { get; set; }
        public bool CreateDailyRemark { get; set; }
        public bool ViewDailyRemark { get; set; }
        public bool SaleTarget { get; set; }
        public bool CreateLeadSetting { get; set; }
        public bool ViewLeadSetting { get; set; }
        public bool IsEmailSetup { get; set; }
        public bool IsEmailTemplates { get; set; }
        public bool IsEmployeeProfiles { get; set; }
        public bool IsErrorTypes { get; set; }
        public bool IsIndiaMartSetting { get; set; }
        public bool IsInterviewStatus { get; set; }
        public bool IsLeadForm { get; set; }
        public bool IsLeadSource { get; set; }
        public bool IsLeadStatus { get; set; }
        public bool IsLeadsView { get; set; }
        public bool IsProductTypes { get; set; }
        public bool IsTicketForm { get; set; }
        public bool IsTicketsView { get; set; }
        public bool IsUrgencyTypes { get; set; }
        public bool IsManageEmployees { get; set; }
        public bool IsLeaveName { get; set; }
        public bool ViewQuotation { get; set; }
        public bool AddSaleOrder { get; set; }
        public bool ViewSaleOrder { get; set; }
        public Nullable<bool> IsProjectStatus { get; set; }
    }
}
