//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Svam.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class crm_workdescriptiontbl
    {
        public long Id { get; set; }
        public Nullable<long> WorkId { get; set; }
        public int WorkStatus { get; set; }
        public string Description { get; set; }
        public string WorkAttachment { get; set; }
        public Nullable<int> BranchId { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public string FollowUpTime { get; set; }
        public Nullable<System.DateTime> FollowDate { get; set; }
    }
}
