//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Svam.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class crm_createleadsetting
    {
        public long Id { get; set; }
        public int CompanyID { get; set; }
        public int BranchID { get; set; }
        public bool IsCustomer { get; set; }
        public bool IsDesignation { get; set; }
        public bool IsMobileNo { get; set; }
        public bool IsEmailId { get; set; }
        public bool IsLeadResource { get; set; }
        public bool IsLeadStatus { get; set; }
        public bool IsProductType { get; set; }
        public bool IsOrganizationName { get; set; }
        public bool IsTimeZoneName { get; set; }
        public bool IsFollowupDate { get; set; }
        public bool IsFollowUpTime { get; set; }
        public bool IsFollowupTimeinIST { get; set; }
        public bool IsCountry { get; set; }
        public bool IsCity { get; set; }
        public bool IsState { get; set; }
        public bool IsAddress { get; set; }
        public bool IsUrl { get; set; }
        public bool IsSkypeId { get; set; }
        public bool IsDescription { get; set; }
        public bool IsActive { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public bool IsDateofBirth { get; set; }
        public bool IsMarriageAnniversary { get; set; }
        public bool IsExpectedClosingDate { get; set; }
        public bool IsExpectedDealAmount { get; set; }
        public bool IsExtraCol1 { get; set; }
        public bool IsExtraCol2 { get; set; }
        public bool IsExtraCol3 { get; set; }
        public bool IsExtraCol4 { get; set; }
        public bool IsExtraCol5 { get; set; }
        public bool IsExtraCol6 { get; set; }
        public bool IsExtraCol7 { get; set; }
        public bool IsExtraCol8 { get; set; }
        public bool IsExtraCol9 { get; set; }
        public bool IsExtraCol10 { get; set; }
        public bool IsExtraCol1Mandatory { get; set; }
        public bool IsExtraCol2Mandatory { get; set; }
        public bool IsExtraCol3Mandatory { get; set; }
        public bool IsExtraCol4Mandatory { get; set; }
        public bool IsExtraCol5Mandatory { get; set; }
        public bool IsExtraCol6Mandatory { get; set; }
        public bool IsExtraCol7Mandatory { get; set; }
        public bool IsExtraCol8Mandatory { get; set; }
        public bool IsExtraCol9Mandatory { get; set; }
        public bool IsExtraCol10Mandatory { get; set; }
        public bool IsDesigMandatory { get; set; }
        public bool IsEmailMandatory { get; set; }
        public bool IsLdResMandatory { get; set; }
        public bool IsLdStatusMandatory { get; set; }
        public bool IsProdTypeMandatory { get; set; }
        public bool IsOrgNameMandatory { get; set; }
        public bool IsTZNameMandatory { get; set; }
        public bool IsFUpTimeMandatory { get; set; }
        public bool IsFupTimeinISTMandatory { get; set; }
        public bool IsCountryMandatory { get; set; }
        public bool IsCityMandatory { get; set; }
        public bool IsStateMandatory { get; set; }
        public bool IsAddressMandatory { get; set; }
        public bool IsUrlMandatory { get; set; }
        public bool IsSkypeIdMandatory { get; set; }
        public bool IsDOBMandatory { get; set; }
        public bool IsMrgAniMandatory { get; set; }
        public bool IsExpClsDateMandatory { get; set; }
        public bool IsExpDealAmtMandatory { get; set; }
        public bool IsExtraCol11 { get; set; }
        public bool IsExtraCol12 { get; set; }
        public bool IsExtraCol13 { get; set; }
        public bool IsExtraCol14 { get; set; }
        public bool IsExtraCol15 { get; set; }
        public bool IsExtraCol16 { get; set; }
        public bool IsExtraCol17 { get; set; }
        public bool IsExtraCol18 { get; set; }
        public bool IsExtraCol19 { get; set; }
        public bool IsExtraCol20 { get; set; }
        public bool IsExtraCol11Mandatory { get; set; }
        public bool IsExtraCol12Mandatory { get; set; }
        public bool IsExtraCol13Mandatory { get; set; }
        public bool IsExtraCol14Mandatory { get; set; }
        public bool IsExtraCol15Mandatory { get; set; }
        public bool IsExtraCol16Mandatory { get; set; }
        public bool IsExtraCol17Mandatory { get; set; }
        public bool IsExtraCol18Mandatory { get; set; }
        public bool IsExtraCol19Mandatory { get; set; }
        public bool IsExtraCol20Mandatory { get; set; }
        public bool IsWhatsAppNo { get; set; }
        public bool IsExtraCol1dropdown { get; set; }
        public bool IsExtraCol2dropdown { get; set; }
        public bool IsExtraCol3dropdown { get; set; }
        public bool IsExtraCol4dropdown { get; set; }
        public bool IsExtraCol5dropdown { get; set; }
        public bool IsExtraCol1dropdownMandatory { get; set; }
        public bool IsExtraCol2dropdownMandatory { get; set; }
        public bool IsExtraCol3dropdownMandatory { get; set; }
        public bool IsExtraCol4dropdownMandatory { get; set; }
        public bool IsExtraCol5dropdownMandatory { get; set; }
    }
}
