//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Svam.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class crm_mappeduserotherbranch
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public int MappedUserId { get; set; }
        public System.DateTime CreateDate { get; set; }
        public bool IsActive { get; set; }
    }
}
