//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Svam.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class crm_createleadstbl
    {
        public long Id { get; set; }
        public Nullable<int> LeadOwner { get; set; }
        public string Customer { get; set; }
        public string Designation { get; set; }
        public string MobileNo { get; set; }
        public string EmailId { get; set; }
        public string OtherNo { get; set; }
        public string DNDStatus { get; set; }
        public string LeadsType { get; set; }
        public Nullable<int> LeadSourceID { get; set; }
        public string LeadResource { get; set; }
        public Nullable<int> LeadStatusID { get; set; }
        public string LeadStatus { get; set; }
        public Nullable<int> ProductTypeID { get; set; }
        public string ProductTypeName { get; set; }
        public string OrganizationName { get; set; }
        public string ZoneName { get; set; }
        public Nullable<System.DateTime> FollowDate { get; set; }
        public string FollowUpTime { get; set; }
        public string FollowupTimeinIST { get; set; }
        public string Country { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Address { get; set; }
        public string Url { get; set; }
        public string SkypeId { get; set; }
        public string OtherRemarks { get; set; }
        public string Description { get; set; }
        public string AssignTo { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<bool> Status { get; set; }
        public string date { get; set; }
        public Nullable<System.DateTime> Createddate { get; set; }
        public Nullable<bool> Notify { get; set; }
        public string NotifybyUser { get; set; }
        public Nullable<System.DateTime> NotifyDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<System.DateTime> AssignedDate { get; set; }
        public string AssignedBy { get; set; }
        public Nullable<int> CompanyID { get; set; }
        public Nullable<int> BranchID { get; set; }
        public Nullable<int> CountryID { get; set; }
        public Nullable<int> StateID { get; set; }
        public Nullable<int> CityID { get; set; }
        public string DateofBirth { get; set; }
        public string MarriageAnniversary { get; set; }
        public Nullable<System.DateTime> ExpectedDate { get; set; }
        public decimal ExpectedProductAmount { get; set; }
        public string ExtraCol1 { get; set; }
        public string ExtraCol2 { get; set; }
        public string ExtraCol3 { get; set; }
        public string ExtraCol4 { get; set; }
        public string ExtraCol5 { get; set; }
        public Nullable<decimal> ExtraCol6 { get; set; }
        public Nullable<int> ExtraCol7 { get; set; }
        public Nullable<int> ExtraCol8 { get; set; }
        public Nullable<System.DateTime> ExtraCol9 { get; set; }
        public Nullable<System.DateTime> ExtraCol10 { get; set; }
        public Nullable<decimal> ExtraCol11 { get; set; }
        public Nullable<decimal> ExtraCol12 { get; set; }
        public Nullable<decimal> ExtraCol13 { get; set; }
        public Nullable<decimal> ExtraCol14 { get; set; }
        public Nullable<int> ExtraCol15 { get; set; }
        public Nullable<int> ExtraCol16 { get; set; }
        public Nullable<int> ExtraCol17 { get; set; }
        public Nullable<System.DateTime> ExtraCol18 { get; set; }
        public Nullable<System.DateTime> ExtraCol19 { get; set; }
        public Nullable<System.DateTime> ExtraCol20 { get; set; }
        public bool IsLeadReminder { get; set; }
        public Nullable<System.DateTime> ConvertedFupDateTime { get; set; }
        public string PastPerformance { get; set; }
        public string ProfitLoss { get; set; }
        public string BuySell { get; set; }
        public string StockName { get; set; }
        public string Price { get; set; }
        public string Target { get; set; }
        public string Target2 { get; set; }
        public string Target3 { get; set; }
        public string SI { get; set; }
        public string Remark { get; set; }
        public Nullable<int> ExtraCol1dropdown1Id { get; set; }
        public string Dp1name { get; set; }
        public string Dp2name { get; set; }
        public string Dp3name { get; set; }
        public string Dp4name { get; set; }
        public string Dp5name { get; set; }
        public Nullable<int> Extracol1dropdownId1 { get; set; }
        public Nullable<int> Extracol1dropdownId2 { get; set; }
        public Nullable<int> Extracol1dropdownId3 { get; set; }
        public Nullable<int> Extracol1dropdownId4 { get; set; }
        public Nullable<int> Extracol1dropdownId5 { get; set; }
    }
}
