//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Svam.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class crm_assignitemtypeuser
    {
        public int Id { get; set; }
        public Nullable<int> ItemTypeId { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> CompanyID { get; set; }
        public Nullable<int> BranchID { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<decimal> Estimated_Cost { get; set; }
        public Nullable<System.DateTime> Expirydate { get; set; }
        public string CheckStatus { get; set; }
        public string SerialNo { get; set; }
        public Nullable<System.DateTime> Assigndate { get; set; }
    }
}
