//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Svam.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class crm_interviewscheduletbl
    {
        public long Id { get; set; }
        public Nullable<int> UID { get; set; }
        public string CandidateName { get; set; }
        public string ResumeId { get; set; }
        public string PostalAddress { get; set; }
        public string Telephone { get; set; }
        public string MobileNo { get; set; }
        public string DateOfBirth { get; set; }
        public string Email { get; set; }
        public string WorkExperiance { get; set; }
        public string ResumeTitle { get; set; }
        public string CurrentLocation { get; set; }
        public string PreferredLocation { get; set; }
        public string CurrentEmployer { get; set; }
        public string CurrentDesignation { get; set; }
        public string AnnualSalary { get; set; }
        public string UGCourses { get; set; }
        public string PGCourses { get; set; }
        public string PPGCourses { get; set; }
        public string LastActiveDate { get; set; }
        public Nullable<int> Profile { get; set; }
        public string FollowUpDate { get; set; }
        public string InterViewDate { get; set; }
        public string Remarks { get; set; }
        public string Status { get; set; }
        public string CreateDate { get; set; }
        public Nullable<System.DateTime> Created_at { get; set; }
        public Nullable<int> BranchID { get; set; }
        public Nullable<int> CompanyID { get; set; }
    }
}
