//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Svam.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class crm_assignedtootherorganization
    {
        public long Id { get; set; }
        public int AssignToCompanyID { get; set; }
        public Nullable<int> AssignedUserID { get; set; }
        public int AssignedBy { get; set; }
        public System.DateTime AssignedDate { get; set; }
        public bool IsActive { get; set; }
    }
}
