//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Svam.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class crm_tickets
    {
        public long TicketID { get; set; }
        public string TicketNo { get; set; }
        public string Name { get; set; }
        public string EmailID { get; set; }
        public string PhoneNumber { get; set; }
        public Nullable<int> ErrorTypeID { get; set; }
        public Nullable<int> ProductTypeID { get; set; }
        public Nullable<int> UrgencyID { get; set; }
        public string subject { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<int> StatusID { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public Nullable<int> BranchID { get; set; }
        public Nullable<int> AssignedTo { get; set; }
        public Nullable<int> AssignedBy { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public bool IsCustomerTbl { get; set; }
        public int EscalateLevel { get; set; }
        public Nullable<System.DateTime> AssignedDate { get; set; }
        public string ExtraCol1 { get; set; }
        public string ExtraCol2 { get; set; }
        public string ExtraCol3 { get; set; }
        public string ExtraCol4 { get; set; }
        public string ExtraCol5 { get; set; }
        public string ExtraCol6 { get; set; }
        public decimal ExtraCol7 { get; set; }
        public decimal ExtraCol8 { get; set; }
        public Nullable<System.DateTime> ExtraCol9 { get; set; }
        public Nullable<System.DateTime> ExtraCol10 { get; set; }
        public int ExtraCol11 { get; set; }
        public int ExtraCol12 { get; set; }
        public string ImageCol1 { get; set; }
        public string ImageCol2 { get; set; }
        public string ImageCol3 { get; set; }
        public string ImageCol4 { get; set; }
        public string Extracoldropdown1 { get; set; }
        public string Extracoldropdown2 { get; set; }
        public string Extracoldropdown3 { get; set; }
        public string Extracoldropdown4 { get; set; }
        public string Extracoldropdown5 { get; set; }
        public string Sparepartstatus { get; set; }
    }
}
