//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Svam.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class crm_ticketcreatesetting
    {
        public int Id { get; set; }
        public bool IsName { get; set; }
        public bool IsEmailID { get; set; }
        public bool IsPhoneNumber { get; set; }
        public bool IsErrorTypeID { get; set; }
        public bool IsProductTypeID { get; set; }
        public bool IsUrgencyID { get; set; }
        public bool Issubject { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public bool IsStatusID { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public Nullable<int> BranchID { get; set; }
        public bool IsCustomerID { get; set; }
        public bool IsExtraCol1 { get; set; }
        public bool IsExtraCol2 { get; set; }
        public bool IsExtraCol3 { get; set; }
        public bool IsExtraCol4 { get; set; }
        public bool IsExtraCol5 { get; set; }
        public bool ISExtraCol6 { get; set; }
        public bool ISExtraCol7 { get; set; }
        public bool ISExtraCol8 { get; set; }
        public bool IsExtraCol9 { get; set; }
        public bool IsExtraCol10 { get; set; }
        public bool IsExtraCol11 { get; set; }
        public bool IsExtraCol12 { get; set; }
        public bool IsImageCol1 { get; set; }
        public bool IsImageCol2 { get; set; }
        public bool IsImageCol3 { get; set; }
        public bool IsImageCol4 { get; set; }
        public bool IsEmailIDRequired { get; set; }
        public bool IsErrorTypeIDRequired { get; set; }
        public bool IsProductTypeIDRequired { get; set; }
        public bool IsUrgencyIDRequired { get; set; }
        public bool IssubjectRequired { get; set; }
        public bool IsStatusIDRequired { get; set; }
        public bool IsCustomerIDRequired { get; set; }
        public bool IsExtraCol1Required { get; set; }
        public bool IsExtraCol2Required { get; set; }
        public bool IsExtraCol3Required { get; set; }
        public bool IsExtraCol4Required { get; set; }
        public bool IsExtraCol5Required { get; set; }
        public bool ISExtraCol6Required { get; set; }
        public bool ISExtraCol7Required { get; set; }
        public bool ISExtraCol8Required { get; set; }
        public bool IsExtraCol9Required { get; set; }
        public bool IsExtraCol10Required { get; set; }
        public bool IsExtraCol11Required { get; set; }
        public bool IsExtraCol12Required { get; set; }
        public bool IsImageCol1Required { get; set; }
        public bool IsImageCol2Required { get; set; }
        public bool IsImageCol3Required { get; set; }
        public bool IsImageCol4Required { get; set; }
        public bool IsTicketFilesImages { get; set; }
        public bool IsTicketFilesImagesRequired { get; set; }
        public bool IsExtraColdropdown1 { get; set; }
        public bool IsExtraColdropdown2 { get; set; }
        public bool IsExtraColdropdown3 { get; set; }
        public bool IsExtraColdropdown4 { get; set; }
        public bool IsExtraColdropdown5 { get; set; }
        public bool IsExtraColdropdown1Required { get; set; }
        public bool IsExtraColdropdown2Required { get; set; }
        public bool IsExtraColdropdown3Required { get; set; }
        public bool IsExtraColdropdown4Required { get; set; }
        public bool IsExtraColdropdown5Required { get; set; }
    }
}
