//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Svam.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class crm_leadassignhistorytbl
    {
        public long Id { get; set; }
        public Nullable<long> LeadId { get; set; }
        public Nullable<int> LeadAssignBy { get; set; }
        public Nullable<int> LeadAssignTo { get; set; }
        public string LeadAssignDate { get; set; }
        public string LeadStatus { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> BranchID { get; set; }
        public Nullable<int> CompanyID { get; set; }
        public Nullable<int> LeadStatusID { get; set; }
    }
}
