//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Svam.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class crm_leaddropdownlist_tbl
    {
        public string DropdownName { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<int> CompanyID { get; set; }
        public Nullable<int> BranchID { get; set; }
        public string DropDownfield { get; set; }
        public string DropDownItemNamw { get; set; }
        public Nullable<bool> Status { get; set; }
        public int dropddownItemId { get; set; }
    }
}
