//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Svam.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class crm_tbl_nipl_emp_attendance
    {
        public long ID { get; set; }
        public Nullable<int> EmpId { get; set; }
        public string L_In_Date { get; set; }
        public string L_In_Time { get; set; }
        public string L_Out_Date { get; set; }
        public string L_Out_Time { get; set; }
        public string Duration { get; set; }
        public Nullable<bool> Working_Late_Night { get; set; }
        public Nullable<bool> Extra_working { get; set; }
        public string IPAddress { get; set; }
        public string MacAddress { get; set; }
        public string LogTimeZone { get; set; }
        public string Status { get; set; }
        public Nullable<int> BranchID { get; set; }
        public Nullable<int> CompanyID { get; set; }
        public string AttendanceType { get; set; }
    }
}
