//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Svam.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class crm_tbl_nipldeveloper_dailyreort
    {
        public long Id { get; set; }
        public Nullable<int> UID { get; set; }
        public Nullable<long> Project_ID { get; set; }
        public Nullable<int> ProjectModule_ID { get; set; }
        public string GeneralRemark { get; set; }
        public string CodeModuleRemark { get; set; }
        public string DBModuleRemark { get; set; }
        public string JsModuleRemark { get; set; }
        public string SupportNeeded { get; set; }
        public string CodeFile { get; set; }
        public string CreatedDate { get; set; }
        public Nullable<bool> status { get; set; }
        public Nullable<int> BranchID { get; set; }
        public Nullable<int> CompanyID { get; set; }
    }
}
