//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Svam.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class crm_zonetbl
    {
        public int Id { get; set; }
        public string ZoneName { get; set; }
        public int ZoneHours { get; set; }
        public int ZoneMin { get; set; }
        public bool Status { get; set; }
    }
}
