//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Svam.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class crm_leaverequest_tbl
    {
        public long Id { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public Nullable<int> LeaveTypeID { get; set; }
        public string Subject { get; set; }
        public string Message { get; set; }
        public Nullable<System.DateTime> RequestDate { get; set; }
        public string ProcessStatus { get; set; }
        public Nullable<System.DateTime> ProcessDate { get; set; }
        public string Comment { get; set; }
        public Nullable<int> BranchID { get; set; }
        public Nullable<int> CompanyID { get; set; }
    }
}
