//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Svam.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class crm_leadsupdatetblhistory
    {
        public long Id { get; set; }
        public Nullable<int> LeadOwner { get; set; }
        public string Customer { get; set; }
        public string MobileNo { get; set; }
        public string EmailId { get; set; }
        public string OtherNo { get; set; }
        public Nullable<int> LeadSourceID { get; set; }
        public string LeadResource { get; set; }
        public Nullable<int> LeadStatusID { get; set; }
        public string LeadStatus { get; set; }
        public Nullable<int> ProductTypeId { get; set; }
        public string Designation { get; set; }
        public string OrganizationName { get; set; }
        public string ZoneName { get; set; }
        public Nullable<System.DateTime> FollowDate { get; set; }
        public string FollowUpTime { get; set; }
        public string FollowupTimeinIST { get; set; }
        public string Country { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Address { get; set; }
        public string Url { get; set; }
        public string SkypeId { get; set; }
        public string OtherRemarks { get; set; }
        public string Description { get; set; }
        public string AssignTo { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<bool> Status { get; set; }
        public string date { get; set; }
        public Nullable<System.DateTime> Createddate { get; set; }
        public string LeadsType { get; set; }
        public Nullable<System.DateTime> HistoryDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<int> BranchID { get; set; }
        public Nullable<int> CompanyID { get; set; }
        public Nullable<int> CountryID { get; set; }
        public Nullable<int> StateID { get; set; }
        public Nullable<int> CityID { get; set; }
    }
}
