//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Svam.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class crm_saledetailtbl
    {
        public int ID { get; set; }
        public string PROJECTDESCRIPTION { get; set; }
        public Nullable<decimal> PROJECTVALUE { get; set; }
        public Nullable<decimal> ADVANCEPAYMENT { get; set; }
        public string ADVANCEPAYMENTDATE { get; set; }
        public string CHEQUENO { get; set; }
        public string PROJECTCOMPLETIONDATE { get; set; }
        public string EXPIRYDATE { get; set; }
        public string LICENSE { get; set; }
        public Nullable<long> FK_LEADID { get; set; }
        public Nullable<int> FK_CREATEDBY { get; set; }
        public Nullable<System.DateTime> CREATEDDATE { get; set; }
        public Nullable<System.DateTime> CREATEDDATETIME { get; set; }
        public Nullable<int> BranchID { get; set; }
        public Nullable<int> CompanyID { get; set; }
    }
}
