//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Svam.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class crm_ticketfieldnamecustomized
    {
        public int Id { get; set; }
        public string TicketNoText { get; set; }
        public string NameText { get; set; }
        public string EmailIDText { get; set; }
        public string PhoneNumberText { get; set; }
        public string ErrorTypeIDText { get; set; }
        public string ProductTypeIDText { get; set; }
        public string UrgencyIDText { get; set; }
        public string subjectText { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public string StatusIDText { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public Nullable<int> BranchID { get; set; }
        public string AssignedToText { get; set; }
        public string CustomerIDText { get; set; }
        public string ExtraCol1Text { get; set; }
        public string ExtraCol2Text { get; set; }
        public string ExtraCol3Text { get; set; }
        public string ExtraCol4Text { get; set; }
        public string ExtraCol5Text { get; set; }
        public string ExtraCol6Text { get; set; }
        public string ExtraCol7Text { get; set; }
        public string ExtraCol8Text { get; set; }
        public string ExtraCol9Text { get; set; }
        public string ExtraCol10Text { get; set; }
        public string ExtraCol11Text { get; set; }
        public string ExtraCol12Text { get; set; }
        public string ImageCol1Text { get; set; }
        public string ImageCol2Text { get; set; }
        public string ImageCol3Text { get; set; }
        public string ImageCol4Text { get; set; }
        public string TicketFilesImagesText { get; set; }
        public string ExtraColdropdown1Text { get; set; }
        public string ExtraColdropdown2Text { get; set; }
        public string ExtraColdropdown3Text { get; set; }
        public string ExtraColdropdown4Text { get; set; }
        public string ExtraColdropdown5Text { get; set; }
    }
}
