//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Svam.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class crm_ticketremarkforteam
    {
        public long Id { get; set; }
        public long TicketId { get; set; }
        public string Message { get; set; }
        public string AttachmentFile { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public int CreatedBy { get; set; }
        public string StatusName { get; set; }
        public int CompanyID { get; set; }
        public int BranchId { get; set; }
    }
}
