//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Svam.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class crm_tracksaleperson
    {
        public long TrackID { get; set; }
        public Nullable<int> UserID { get; set; }
        public string Address { get; set; }
        public string Country { get; set; }
        public string StateName { get; set; }
        public string CityName { get; set; }
        public string Latitude { get; set; }
        public string Longitude { get; set; }
        public Nullable<System.DateTime> TrackDatetime { get; set; }
    }
}
