//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Svam.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class crm_ticketviewsetting
    {
        public int Id { get; set; }
        public bool IsName { get; set; }
        public bool IsEmailID { get; set; }
        public bool IsPhoneNumber { get; set; }
        public bool IsErrorTypeID { get; set; }
        public bool IsProductTypeID { get; set; }
        public bool IsUrgencyID { get; set; }
        public bool Issubject { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public bool IsStatusID { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public Nullable<int> BranchID { get; set; }
        public bool IsCreatedBy { get; set; }
        public bool IsCreatedDate { get; set; }
        public bool IsAssignedTo { get; set; }
        public bool IsAssignedBy { get; set; }
        public bool IsModifiedDate { get; set; }
        public bool IsCustomerID { get; set; }
        public bool IsExtraCol1 { get; set; }
        public bool IsExtraCol2 { get; set; }
        public bool IsExtraCol3 { get; set; }
        public bool IsExtraCol4 { get; set; }
        public bool IsExtraCol5 { get; set; }
        public bool ISExtraCol6 { get; set; }
        public bool ISExtraCol7 { get; set; }
        public bool ISExtraCol8 { get; set; }
        public bool IsExtraCol9 { get; set; }
        public bool IsExtraCol10 { get; set; }
        public bool IsExtraCol11 { get; set; }
        public bool IsExtraCol12 { get; set; }
        public bool IsImageCol1 { get; set; }
        public bool IsImageCol2 { get; set; }
        public bool IsImageCol3 { get; set; }
        public bool IsImageCol4 { get; set; }
        public bool IsExtracoldropdown1 { get; set; }
        public bool IsExtracoldropdown2 { get; set; }
        public bool IsExtracoldropdown3 { get; set; }
        public bool IsExtracoldropdown4 { get; set; }
        public bool IsExtracoldropdown5 { get; set; }
    }
}
