//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Svam.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class crm_customizedformfieldtextname
    {
        public long Id { get; set; }
        public string LeadOwnerTextName { get; set; }
        public string CustomerTextName { get; set; }
        public string DesignationTextName { get; set; }
        public string MobileNoTextName { get; set; }
        public string EmailIdTextName { get; set; }
        public string OtherNoTextName { get; set; }
        public string DNDStatusTextName { get; set; }
        public string LeadsTypeTextName { get; set; }
        public string LeadResourceTextName { get; set; }
        public string LeadStatusTextName { get; set; }
        public string ProductTypeNameTextName { get; set; }
        public string OrganizationNameTextName { get; set; }
        public string ZoneNameTextName { get; set; }
        public string FollowDateTextName { get; set; }
        public string FollowUpTimeTextName { get; set; }
        public string FollowupTimeinISTTextName { get; set; }
        public string AddressTextNameTextName { get; set; }
        public string UrlTextName { get; set; }
        public string SkypeIdTextName { get; set; }
        public string FormTextName { get; set; }
        public string DescriptionTextName { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public bool Status { get; set; }
        public Nullable<System.DateTime> Createddate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> CompanyID { get; set; }
        public Nullable<int> BranchID { get; set; }
        public string DateofBirthTextName { get; set; }
        public string MarriageAnniversaryTextName { get; set; }
        public string ExpectedDateTextName { get; set; }
        public string ExpectedProductAmountTextName { get; set; }
        public string ExtraCol1TextName { get; set; }
        public string ExtraCol2TextName { get; set; }
        public string ExtraCol3TextName { get; set; }
        public string ExtraCol4TextName { get; set; }
        public string ExtraCol5TextName { get; set; }
        public string ExtraCol6TextName { get; set; }
        public string ExtraCol7TextName { get; set; }
        public string ExtraCol8TextName { get; set; }
        public string ExtraCol9TextName { get; set; }
        public string ExtraCol10TextName { get; set; }
        public string HeaderMenuTextName { get; set; }
        public string CountryTextName { get; set; }
        public string StateTextName { get; set; }
        public string CityTextName { get; set; }
        public string ExtraCol11TextName { get; set; }
        public string ExtraCol12TextName { get; set; }
        public string ExtraCol13TextName { get; set; }
        public string ExtraCol14TextName { get; set; }
        public string ExtraCol15TextName { get; set; }
        public string ExtraCol16TextName { get; set; }
        public string ExtraCol17TextName { get; set; }
        public string ExtraCol18TextName { get; set; }
        public string ExtraCol19TextName { get; set; }
        public string ExtraCol20TextName { get; set; }
        public string ExtraCol1dropdown { get; set; }
        public string ExtraCol2dropdown { get; set; }
        public string ExtraCol3dropdown { get; set; }
        public string ExtraCol4dropdown { get; set; }
        public string ExtraCol5dropdown { get; set; }
    }
}
