//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Svam.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class crm_ticketdropdownlist_tbl
    {
        public int T_DropdownitemId { get; set; }
        public string T_DropdownName { get; set; }
        public Nullable<System.DateTime> T_created_at { get; set; }
        public Nullable<int> T_CompanyID { get; set; }
        public Nullable<int> T_BranchID { get; set; }
        public string T_DropDownfield { get; set; }
        public string T_DropDownItemName { get; set; }
        public Nullable<bool> Status { get; set; }
    }
}
