//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Svam.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class customer_ledger
    {
        public int ID { get; set; }
        public float OpeningBalance { get; set; }
        public float ItemTotal { get; set; }
        public float Cash { get; set; }
        public float Cheque { get; set; }
        public float Credit { get; set; }
        public float ReturnedAmount { get; set; }
        public float ClosingBalance { get; set; }
        public int CustomerID { get; set; }
        public string ChallanNo { get; set; }
        public string Dated { get; set; }
        public Nullable<int> branchcode { get; set; }
        public string companyID { get; set; }
        public string flag { get; set; }
        public string SyncID { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    }
}
