//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Svam.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class customerpayinfo
    {
        public int id { get; set; }
        public string VoucherNo { get; set; }
        public string SaleReturnVoucherNo { get; set; }
        public Nullable<System.DateTime> VoucherDt { get; set; }
        public string CustomerName { get; set; }
        public string CustomerCode { get; set; }
        public Nullable<decimal> TenderAmt { get; set; }
        public string BranchCode { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public decimal openingbalance { get; set; }
        public decimal closingbalance { get; set; }
        public string Other1 { get; set; }
        public string Other2 { get; set; }
        public string Other3 { get; set; }
        public Nullable<decimal> Other4 { get; set; }
        public Nullable<decimal> Other5 { get; set; }
        public Nullable<int> CompanyID { get; set; }
        public string flag { get; set; }
        public Nullable<System.DateTime> chequedate { get; set; }
        public string bankname { get; set; }
        public string narration { get; set; }
        public string SyncID { get; set; }
        public string SystemVoucherNo { get; set; }
        public Nullable<decimal> bill_ledger_balance { get; set; }
        public Nullable<decimal> AdjustedAmt { get; set; }
    }
}
