//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Svam.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class customer
    {
        public int ID { get; set; }
        public string CustomerID { get; set; }
        public string LoyaltyTypeID { get; set; }
        public string CustomerName { get; set; }
        public string bride_name { get; set; }
        public string bride_groom_name { get; set; }
        public string birthday_person_name { get; set; }
        public string area_wise { get; set; }
        public string LoyaltyCardNo { get; set; }
        public string BillingAddress { get; set; }
        public string DeliveryAddress { get; set; }
        public Nullable<int> Country { get; set; }
        public Nullable<int> City { get; set; }
        public Nullable<int> State { get; set; }
        public string PhoneNo { get; set; }
        public string MobileNo { get; set; }
        public string EmailID { get; set; }
        public string Sex { get; set; }
        public string DateOfBirth { get; set; }
        public string MaritalStatus { get; set; }
        public string Anniversary { get; set; }
        public string Company { get; set; }
        public string CompanyID { get; set; }
        public string SendPromotionalOffer { get; set; }
        public string Remarks { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> BranchCode { get; set; }
        public Nullable<int> Photo { get; set; }
        public string OfficePhoneNo { get; set; }
        public string AltMobileNo { get; set; }
        public string SpouseMobileNo { get; set; }
        public Nullable<decimal> CreditLimit { get; set; }
        public Nullable<int> mastercode { get; set; }
        public Nullable<decimal> openingbalance { get; set; }
        public string crdr { get; set; }
        public Nullable<decimal> AdvanceAmount { get; set; }
        public string flag { get; set; }
        public string SyncID { get; set; }
        public Nullable<int> CrmCustomerID { get; set; }
        public string Pincode { get; set; }
        public string BusinessType { get; set; }
        public string ContactPerson { get; set; }
        public string ContactPhone { get; set; }
        public string ContactDesignation { get; set; }
        public string site_name { get; set; }
        public string site_address { get; set; }
        public string isActive { get; set; }
        public string route { get; set; }
        public Nullable<int> sales_person { get; set; }
        public string drug_license_number { get; set; }
    }
}
