//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Svam.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class customersadvance
    {
        public int ID { get; set; }
        public string CustomerID { get; set; }
        public string CustomerName { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> BranchCode { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public Nullable<decimal> AdvanceAmount { get; set; }
        public Nullable<decimal> Other1 { get; set; }
        public string ReceiptNo { get; set; }
        public Nullable<decimal> DeductAmount { get; set; }
        public string flag { get; set; }
        public string SyncID { get; set; }
    }
}
