//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Svam.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class dashboard
    {
        public int Dashboard_ID { get; set; }
        public string Dashboard_Name { get; set; }
        public int Dashboard_Value { get; set; }
        public sbyte Status { get; set; }
    }
}
