//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Svam.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class departmentdetail
    {
        public int id { get; set; }
        public string VoucherNo { get; set; }
        public Nullable<System.DateTime> VoucherDt { get; set; }
        public string department { get; set; }
        public string departmentCode { get; set; }
        public string perticular { get; set; }
        public decimal Qnty { get; set; }
        public decimal Rate { get; set; }
        public string unit { get; set; }
        public decimal amount { get; set; }
        public string SyncID { get; set; }
        public string flag { get; set; }
    }
}
