//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Svam.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class discount_coupon
    {
        public int id { get; set; }
        public string coupon_code { get; set; }
        public string discountType { get; set; }
        public int discountVal { get; set; }
        public System.DateTime valid_till { get; set; }
        public int voucherCount { get; set; }
        public System.DateTime created { get; set; }
        public int company_id { get; set; }
        public int branch { get; set; }
        public string for_user { get; set; }
        public int status { get; set; }
    }
}
