//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Svam.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class einvoicesetup
    {
        public int ID { get; set; }
        public int CompanyId { get; set; }
        public int BranchCode { get; set; }
        public string gstin_number { get; set; }
        public string code { get; set; }
        public string status { get; set; }
        public string message { get; set; }
        public int mastercompany { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string Flag { get; set; }
        public string SyncID { get; set; }
    }
}
