//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Svam.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class emp_details
    {
        public int ID { get; set; }
        public string EmpId { get; set; }
        public string EmpNM { get; set; }
        public string FatherNm { get; set; }
        public string EmpGrade { get; set; }
        public string Designation { get; set; }
        public string Department { get; set; }
        public string DOJ { get; set; }
        public string DOB { get; set; }
        public string ReportingTO { get; set; }
        public string BloodGrp { get; set; }
        public string Gender { get; set; }
        public string MaritalStatus { get; set; }
        public string AnniversaryDT { get; set; }
        public string Education { get; set; }
        public string PreComp1 { get; set; }
        public string PreComp2 { get; set; }
        public string ValidSt { get; set; }
        public string Resigned { get; set; }
        public string Terminated { get; set; }
        public string IDType { get; set; }
        public string IDNo { get; set; }
        public string CurrentAdd { get; set; }
        public string CopyAdd { get; set; }
        public string PermanentAdd { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string MobileNO { get; set; }
        public string EmailId { get; set; }
        public string EmerContactPer { get; set; }
        public string EmerContactAddress { get; set; }
        public string EmerContactNo { get; set; }
        public Nullable<int> MedicalLeave { get; set; }
        public Nullable<int> CasualLeave { get; set; }
        public string BankAccNo { get; set; }
        public string PancardNo { get; set; }
        public string PFAccNo { get; set; }
        public Nullable<decimal> TotalCTC { get; set; }
        public Nullable<decimal> Basic { get; set; }
        public Nullable<decimal> Conveyance { get; set; }
        public Nullable<decimal> HRA { get; set; }
        public Nullable<decimal> SpecialAllowance { get; set; }
        public Nullable<decimal> MedicalAllowance { get; set; }
        public Nullable<decimal> LeaveTravelAllowance { get; set; }
        public Nullable<decimal> PFAmt { get; set; }
        public Nullable<decimal> CommitionRt { get; set; }
        public Nullable<decimal> CommitssionBase { get; set; }
        public string CreatedBy { get; set; }
        public string CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public string ModifiedDate { get; set; }
        public string SyncID { get; set; }
        public string flag { get; set; }
    }
}
