//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Svam.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class faq_topic
    {
        public int id { get; set; }
        public string name { get; set; }
        public int company_id { get; set; }
        public int branch_id { get; set; }
        public int isActive { get; set; }
    }
}
