//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Svam.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class fgstkline
    {
        public int id { get; set; }
        public string EntryNo { get; set; }
        public string ItemName { get; set; }
        public string ItemCOde { get; set; }
        public string Unit { get; set; }
        public string Barcode { get; set; }
        public Nullable<decimal> Qtyin { get; set; }
        public Nullable<decimal> Deal { get; set; }
        public Nullable<decimal> Weight { get; set; }
        public Nullable<decimal> Qtyout { get; set; }
        public Nullable<decimal> Rate { get; set; }
        public Nullable<decimal> LIneTotal { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public int BranchCode { get; set; }
        public int CompanyId { get; set; }
        public Nullable<decimal> ingrdiantcost { get; set; }
        public Nullable<decimal> LaborCost { get; set; }
        public Nullable<decimal> Energycost { get; set; }
        public Nullable<decimal> OthCost1 { get; set; }
        public Nullable<decimal> SalePrice { get; set; }
        public Nullable<decimal> MRP { get; set; }
        public string size { get; set; }
        public string isactive { get; set; }
        public Nullable<decimal> ReturnQty { get; set; }
        public string fgstklinecolumn1 { get; set; }
        public string fgstklinecolumn2 { get; set; }
        public string fgstklinecolumn3 { get; set; }
        public string fgstklinecolumn4 { get; set; }
        public string fgstklinecolumn5 { get; set; }
        public Nullable<decimal> fgstklinecolumn6 { get; set; }
        public Nullable<decimal> fgstklinecolumn7 { get; set; }
        public Nullable<decimal> fgstklinecolumn8 { get; set; }
        public Nullable<decimal> fgstklinecolumn9 { get; set; }
        public Nullable<decimal> fgstklinecolumn10 { get; set; }
        public string flag { get; set; }
        public string SyncID { get; set; }
        public string SupplierBillNo { get; set; }
        public Nullable<System.DateTime> SupInvDate { get; set; }
        public string CategoryID { get; set; }
        public Nullable<int> SubCatId { get; set; }
        public Nullable<int> SubSubCatId { get; set; }
        public Nullable<int> SubSubSubCatId { get; set; }
        public Nullable<float> cess { get; set; }
        public Nullable<float> cessAmount { get; set; }
        public Nullable<float> Acess { get; set; }
        public Nullable<float> AcessAmount { get; set; }
        public Nullable<float> TcsAmount { get; set; }
    }
}
