//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Svam.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class fgstk
    {
        public int id { get; set; }
        public string EntryNo { get; set; }
        public Nullable<System.DateTime> EntryDt { get; set; }
        public string Department { get; set; }
        public string Division { get; set; }
        public string Location { get; set; }
        public string Remarks { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> branch { get; set; }
        public int CompanyId { get; set; }
        public string column1 { get; set; }
        public string fgstkcolumn2 { get; set; }
        public string fgstkcolumn3 { get; set; }
        public string fgstkcolumn4 { get; set; }
        public string fgstkcolumn5 { get; set; }
        public Nullable<decimal> fgstkcolumn6 { get; set; }
        public Nullable<decimal> fgstkcolumn7 { get; set; }
        public Nullable<decimal> fgstkcolumn8 { get; set; }
        public Nullable<decimal> fgstkcolumn9 { get; set; }
        public Nullable<decimal> fgstkcolumn10 { get; set; }
        public string flag { get; set; }
        public string SyncID { get; set; }
    }
}
