//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Svam.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class financeby
    {
        public int id { get; set; }
        public string financeBy1 { get; set; }
        public string SyncID { get; set; }
        public string flag { get; set; }
    }
}
