//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Svam.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class flipkartproduct
    {
        public long ID { get; set; }
        public int CID { get; set; }
        public int SID { get; set; }
        public string ItemID { get; set; }
        public string Title { get; set; }
        public string FilterTitle { get; set; }
        public string MainCategory { get; set; }
        public string CategoryID { get; set; }
        public string CategoryName { get; set; }
        public string SubTitle { get; set; }
        public string GalleryURL { get; set; }
        public string ViewItemURL { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string SellingStatus { get; set; }
        public string OtherInfo { get; set; }
        public string ItemDescription { get; set; }
        public string SizeVariants { get; set; }
        public string ColorVariants { get; set; }
        public string ProductAPI { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string IsActive { get; set; }
        public string SyncID { get; set; }
        public string flag { get; set; }
    }
}
