//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Svam.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class grnpaid_infoblack
    {
        public int id { get; set; }
        public string VoucherNo { get; set; }
        public Nullable<System.DateTime> VoucherDt { get; set; }
        public string GRNNo { get; set; }
        public Nullable<System.DateTime> GRNDt { get; set; }
        public string Status { get; set; }
        public string SupplierName { get; set; }
        public string SupplierCode { get; set; }
        public Nullable<decimal> Payable { get; set; }
        public Nullable<decimal> Tendered { get; set; }
        public Nullable<decimal> Balance { get; set; }
        public string Particular { get; set; }
        public string SupplierAccNo { get; set; }
        public Nullable<int> PaymentSlipNo { get; set; }
        public string ChallanNo { get; set; }
        public int CustID { get; set; }
        public Nullable<int> branch { get; set; }
        public string CompanyID { get; set; }
        public string flag { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public string CreatedBy { get; set; }
        public string ModifiedBy { get; set; }
        public string SyncID { get; set; }
    }
}
