//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Svam.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class gst_master
    {
        public int Id { get; set; }
        public string GST { get; set; }
        public int Status { get; set; }
        public string CompanyId { get; set; }
        public string BranchCode { get; set; }
        public string CreatedBy { get; set; }
        public string CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public string SyncID { get; set; }
        public string Flag { get; set; }
        public string TaxType { get; set; }
    }
}
