//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Svam.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class interstoretransfer
    {
        public int id { get; set; }
        public string IssueNo { get; set; }
        public string IssueDt { get; set; }
        public string TDep { get; set; }
        public string TDiv { get; set; }
        public string TLoc { get; set; }
        public string FDep { get; set; }
        public string FDiv { get; set; }
        public string FLoc { get; set; }
        public string Rmk { get; set; }
        public string CreatedBy { get; set; }
        public string CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public string ModifiedDate { get; set; }
        public string SyncID { get; set; }
        public string flag { get; set; }
    }
}
