//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Svam.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class interstoretransferline
    {
        public int id { get; set; }
        public string IssueNo { get; set; }
        public string IssueDt { get; set; }
        public string Description { get; set; }
        public string SKU { get; set; }
        public string Unit { get; set; }
        public string Barcode { get; set; }
        public Nullable<long> CurStk { get; set; }
        public Nullable<long> IssueQty { get; set; }
        public string CreatedBy { get; set; }
        public string CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public string ModifiedDate { get; set; }
        public string TDep { get; set; }
        public string TDiv { get; set; }
        public string TLoc { get; set; }
        public Nullable<decimal> Rate { get; set; }
        public string SyncID { get; set; }
        public string flag { get; set; }
    }
}
