//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Svam.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class inv_itemsku
    {
        public int ID { get; set; }
        public string GroupID { get; set; }
        public string DivID { get; set; }
        public string CategoryID { get; set; }
        public string ItemTypeID { get; set; }
        public string ItemName { get; set; }
        public string displayname { get; set; }
        public string SKU { get; set; }
        public string machinesrn { get; set; }
        public string companysrn { get; set; }
        public string Suppliersku { get; set; }
        public string Barcode { get; set; }
        public string UnitID { get; set; }
        public string ColorID { get; set; }
        public string SizeID { get; set; }
        public string LocationID { get; set; }
        public string DepartmentID { get; set; }
        public string Description { get; set; }
        public string StorageTypeID { get; set; }
        public Nullable<double> MinimumStock { get; set; }
        public Nullable<double> SafetyStock { get; set; }
        public Nullable<double> OverStock { get; set; }
        public string ExpiryDuration { get; set; }
        public string Photo { get; set; }
        public string ItemTypeCode { get; set; }
        public string BrandID { get; set; }
        public string ModelNo { get; set; }
        public string PreparationTime { get; set; }
        public string NonVegetarian { get; set; }
        public string SalesItem { get; set; }
        public string ReturnAllowed { get; set; }
        public string Bom_masterid { get; set; }
        public string Active { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<double> BranchCode { get; set; }
        public int CompanyId { get; set; }
        public Nullable<double> UnitPrice { get; set; }
        public Nullable<double> ingrdiantcost { get; set; }
        public Nullable<double> LaborCost { get; set; }
        public Nullable<double> Energycost { get; set; }
        public Nullable<double> OthCost1 { get; set; }
        public Nullable<double> OthCost2 { get; set; }
        public Nullable<double> OthCost3 { get; set; }
        public Nullable<double> OthCost4 { get; set; }
        public string SaleMargin { get; set; }
        public string SPer { get; set; }
        public string SAmt { get; set; }
        public string MarginAmountType { get; set; }
        public string mrpsale_status { get; set; }
        public Nullable<float> purchasegst_amt { get; set; }
        public Nullable<float> salegst_amt { get; set; }
        public string istaxincluded { get; set; }
        public string dis_sale_status { get; set; }
        public Nullable<float> disonmrp { get; set; }
        public Nullable<float> dis_amount { get; set; }
        public Nullable<float> saleprice_includedgst { get; set; }
        public Nullable<float> saleprice_excludedgst { get; set; }
        public string thumbnail_image { get; set; }
        public string thumbnail_image1 { get; set; }
        public string IsActive { get; set; }
        public Nullable<decimal> saleprice { get; set; }
        public string mrpdiscunttype { get; set; }
        public Nullable<decimal> mrpdiscunt { get; set; }
        public string taxincludeinsale { get; set; }
        public Nullable<decimal> CessPer { get; set; }
        public Nullable<decimal> CessAmount { get; set; }
        public Nullable<decimal> PurCessPer { get; set; }
        public string inv_itemskucolumn1 { get; set; }
        public string inv_itemskucolumn2 { get; set; }
        public string inv_itemskucolumn3 { get; set; }
        public string inv_itemskucolumn4 { get; set; }
        public string inv_itemskucolumn5 { get; set; }
        public Nullable<decimal> baseprice { get; set; }
        public Nullable<decimal> basepricedisc { get; set; }
        public Nullable<decimal> inv_itemskucolumn8 { get; set; }
        public Nullable<decimal> inv_itemskucolumn9 { get; set; }
        public Nullable<decimal> inv_itemskucolumn10 { get; set; }
        public string flag { get; set; }
        public byte[] product_image { get; set; }
        public string videoLink { get; set; }
        public string deliveryIn { get; set; }
        public string SyncID { get; set; }
        public string offer { get; set; }
        public string product_selling_ids { get; set; }
        public string item_id { get; set; }
        public string tab_num { get; set; }
        public Nullable<int> SubCatId { get; set; }
        public Nullable<int> SubSubCatId { get; set; }
        public Nullable<int> SubSubSubCatId { get; set; }
        public Nullable<double> MinimumSalePrice { get; set; }
        public Nullable<float> cess { get; set; }
        public string cesstype { get; set; }
        public Nullable<float> Acess { get; set; }
        public string Acesstype { get; set; }
        public Nullable<int> MultyLabelDiscount { get; set; }
        public Nullable<float> height { get; set; }
        public Nullable<float> weight { get; set; }
        public Nullable<float> length { get; set; }
        public Nullable<float> breadth { get; set; }
        public string PriceType { get; set; }
        public Nullable<int> QtyAltFirst { get; set; }
        public Nullable<long> QtyAltSecond { get; set; }
        public string QtyAltFirstMsmt { get; set; }
        public string QtyAltSecondMsmt { get; set; }
        public string comment { get; set; }
        public string SupplierID { get; set; }
        public Nullable<int> status_purchase { get; set; }
        public Nullable<double> MinimumRackStock { get; set; }
        public string item_code { get; set; }
        public string company_name { get; set; }
        public string rack { get; set; }
        public string part_code { get; set; }
        public string item_group { get; set; }
    }
}
