//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Svam.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class inv_inventorystock
    {
        public int InvNO { get; set; }
        public string InvDate { get; set; }
        public string TransactionTypeCode { get; set; }
        public Nullable<int> challanamst_id { get; set; }
        public string material_id { get; set; }
        public string VoucherNo { get; set; }
        public string VoucherDate { get; set; }
        public string SKU { get; set; }
        public string ItemNM { get; set; }
        public string CentreName { get; set; }
        public string Unit { get; set; }
        public string BarcodeNo { get; set; }
        public Nullable<decimal> Weight { get; set; }
        public string WeightUnit { get; set; }
        public Nullable<decimal> QuantityIn { get; set; }
        public Nullable<decimal> Deal { get; set; }
        public Nullable<decimal> QuantityOut { get; set; }
        public Nullable<decimal> Rate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public int BranchCode { get; set; }
        public int CompanyId { get; set; }
        public string Department { get; set; }
        public string Division { get; set; }
        public string Location { get; set; }
        public string TransType { get; set; }
        public Nullable<decimal> Value { get; set; }
        public Nullable<decimal> OutValue { get; set; }
        public Nullable<decimal> Qty { get; set; }
        public Nullable<decimal> SalePrice { get; set; }
        public Nullable<decimal> MRP { get; set; }
        public Nullable<decimal> BundleUnitPrice { get; set; }
        public Nullable<System.DateTime> expiredate { get; set; }
        public Nullable<System.DateTime> mfg_date { get; set; }
        public Nullable<int> validity { get; set; }
        public string batch_no { get; set; }
        public string rackno { get; set; }
        public Nullable<decimal> OpeningStock { get; set; }
        public Nullable<int> TotalBundleQty { get; set; }
        public string ColorID { get; set; }
        public string SizeID { get; set; }
        public string inv_inventorystockcolumn1 { get; set; }
        public string inv_inventorystockcolumn2 { get; set; }
        public string inv_inventorystockcolumn3 { get; set; }
        public string inv_inventorystockcolumn4 { get; set; }
        public string inv_inventorystockcolumn5 { get; set; }
        public Nullable<decimal> inv_inventorystockcol6 { get; set; }
        public Nullable<decimal> inv_inventorystockcol7 { get; set; }
        public Nullable<decimal> inv_inventorystockcol8 { get; set; }
        public Nullable<decimal> inv_inventorystockcolumn9 { get; set; }
        public Nullable<decimal> inv_inventorystockcolumn10 { get; set; }
        public string flag { get; set; }
        public string SyncID { get; set; }
        public string SupplierBillNo { get; set; }
        public string SupplierSubscriptionType { get; set; }
        public Nullable<System.DateTime> SupInvDate { get; set; }
        public string itemsku_id { get; set; }
        public string CategoryID { get; set; }
        public Nullable<int> SubCatId { get; set; }
        public Nullable<int> SubSubCatId { get; set; }
        public Nullable<int> SubSubSubCatId { get; set; }
        public string SystemVoucherNo { get; set; }
        public Nullable<double> MinimumSalePrice { get; set; }
        public Nullable<float> cess { get; set; }
        public string cesstype { get; set; }
        public Nullable<float> Acess { get; set; }
        public string Acesstype { get; set; }
        public Nullable<float> cessAmount { get; set; }
        public Nullable<float> AcessAmount { get; set; }
        public Nullable<float> TcsAmount { get; set; }
        public Nullable<int> item_id { get; set; }
        public string remark { get; set; }
        public Nullable<int> status { get; set; }
    }
}
