//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Svam.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class inv_itemsku_prices
    {
        public long id { get; set; }
        public long inv_itemsku { get; set; }
        public string category_id { get; set; }
        public Nullable<sbyte> type { get; set; }
        public long CompanyId { get; set; }
        public long BranchCode { get; set; }
        public Nullable<float> mrp { get; set; }
        public Nullable<float> saleprice { get; set; }
        public long stock { get; set; }
        public Nullable<float> flipkart_mrp { get; set; }
        public Nullable<float> flipkart_saleprice { get; set; }
        public long flipkart_stock { get; set; }
        public Nullable<float> amazon_mrp { get; set; }
        public Nullable<float> amazon_saleprice { get; set; }
        public long amazon_stock { get; set; }
        public string size { get; set; }
        public string colour { get; set; }
        public string brand { get; set; }
        public string weight { get; set; }
        public string description { get; set; }
        public System.DateTime updated_at { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public long created_by { get; set; }
        public long updated_by { get; set; }
        public byte status { get; set; }
        public string flag { get; set; }
        public string SyncID { get; set; }
    }
}
