//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Svam.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class inv_inventorystock_remove
    {
        public int InvNO { get; set; }
        public string InvDate { get; set; }
        public string TransactionTypeCode { get; set; }
        public Nullable<int> challanamst_id { get; set; }
        public string VoucherNo { get; set; }
        public string VoucherDate { get; set; }
        public string SKU { get; set; }
        public string ItemNM { get; set; }
        public string Unit { get; set; }
        public string BarcodeNo { get; set; }
        public Nullable<decimal> QuantityIn { get; set; }
        public Nullable<decimal> QuantityOut { get; set; }
        public Nullable<decimal> Rate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public int BranchCode { get; set; }
        public int CompanyId { get; set; }
        public string Department { get; set; }
        public string Division { get; set; }
        public string Location { get; set; }
        public string TransType { get; set; }
        public Nullable<decimal> Value { get; set; }
        public Nullable<decimal> OutValue { get; set; }
        public Nullable<decimal> Qty { get; set; }
        public Nullable<decimal> SalePrice { get; set; }
        public Nullable<decimal> MRP { get; set; }
        public Nullable<decimal> BundleUnitPrice { get; set; }
        public Nullable<System.DateTime> expiredate { get; set; }
        public string rackno { get; set; }
        public Nullable<int> OpeningStock { get; set; }
        public Nullable<int> TotalBundleQty { get; set; }
        public string inv_inventorystockcolumn1 { get; set; }
        public string inv_inventorystockcolumn2 { get; set; }
        public string inv_inventorystockcolumn3 { get; set; }
        public string inv_inventorystockcolumn4 { get; set; }
        public string inv_inventorystockcolumn5 { get; set; }
        public Nullable<decimal> inv_inventorystockcol6 { get; set; }
        public Nullable<decimal> inv_inventorystockcol7 { get; set; }
        public Nullable<decimal> inv_inventorystockcol8 { get; set; }
        public Nullable<decimal> inv_inventorystockcolumn9 { get; set; }
        public Nullable<decimal> inv_inventorystockcolumn10 { get; set; }
        public string flag { get; set; }
        public string SyncID { get; set; }
    }
}
