//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Svam.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class inv_itempricecost
    {
        public int ID { get; set; }
        public string SKU { get; set; }
        public decimal UnitPrice { get; set; }
        public Nullable<decimal> TaxID { get; set; }
        public string TaxInclusive { get; set; }
        public string FixedPrice { get; set; }
        public string Active { get; set; }
        public string StartDate { get; set; }
        public string EndDate { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public Nullable<int> BranchCode { get; set; }
        public Nullable<int> CostPriceID { get; set; }
        public string SupplierID { get; set; }
        public Nullable<decimal> MinPOQuantity { get; set; }
        public Nullable<decimal> IngredientCost { get; set; }
        public Nullable<decimal> LabourCost { get; set; }
        public string SyncID { get; set; }
    }
}
