//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Svam.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class inv_fatmawamaster
    {
        public int ID { get; set; }
        public string ItemName { get; set; }
        public string Quantity { get; set; }
        public string Fat { get; set; }
        public string Surcharge { get; set; }
        public string Mawa { get; set; }
        public Nullable<decimal> BasePrice { get; set; }
        public string CreatedBy { get; set; }
        public string CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public string ModifiedDate { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public Nullable<int> BranchCode { get; set; }
        public string Flag { get; set; }
        public string SyncID { get; set; }
    }
}
