//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Svam.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class inv_billofmateriallines
    {
        public int ID { get; set; }
        public string ProductID { get; set; }
        public string ItemID { get; set; }
        public string Sku { get; set; }
        public Nullable<int> Quantity { get; set; }
        public string Unit { get; set; }
        public Nullable<decimal> Expences { get; set; }
        public string VoucherNo { get; set; }
        public string RefVoucherNo { get; set; }
        public Nullable<int> VoucherType { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string ItemGeneratedCentre { get; set; }
        public string ItemConsumedCentre { get; set; }
        public string ItemNameGenerated { get; set; }
        public string QuantityGenerated { get; set; }
        public string UnitGenerated { get; set; }
        public string PriceGenerated { get; set; }
        public string ItemNameConsumed { get; set; }
        public string QuantityConsumed { get; set; }
        public string UnitConsumed { get; set; }
        public string PriceConsumed { get; set; }
        public string Narration { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> CompanyID { get; set; }
        public Nullable<int> BranchCode { get; set; }
        public string Flag { get; set; }
        public string SyncID { get; set; }
    }
}
