//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Svam.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class item_columns_access
    {
        public int ID { get; set; }
        public int user_access_id { get; set; }
        public string user_id { get; set; }
        public string item_column { get; set; }
        public Nullable<int> view { get; set; }
        public Nullable<int> edit { get; set; }
        public Nullable<int> delete { get; set; }
        public int CompanyId { get; set; }
        public int BranchCode { get; set; }
        public string CreatedBy { get; set; }
        public string ModifiedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string IsActive { get; set; }
        public string flag { get; set; }
        public string SyncID { get; set; }
    }
}
