//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Svam.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class item_saleorder
    {
        public int ID { get; set; }
        public string BillNo { get; set; }
        public string QuoNumber { get; set; }
        public string CustomerName { get; set; }
        public string Serial { get; set; }
        public string Particular { get; set; }
        public string SKU { get; set; }
        public string HSN { get; set; }
        public string Color { get; set; }
        public string Size { get; set; }
        public Nullable<decimal> Weight { get; set; }
        public string WeightUnit { get; set; }
        public Nullable<decimal> Qty { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string unit { get; set; }
        public Nullable<decimal> Ourprice { get; set; }
        public Nullable<decimal> mrp { get; set; }
        public Nullable<decimal> Rate { get; set; }
        public Nullable<System.DateTime> Delivery { get; set; }
        public Nullable<decimal> disper { get; set; }
        public Nullable<decimal> disamt { get; set; }
        public Nullable<decimal> gstper { get; set; }
        public Nullable<decimal> gstamt { get; set; }
        public Nullable<decimal> totalamt { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> Createddate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> Modifieddate { get; set; }
        public Nullable<int> CompanyID { get; set; }
        public Nullable<int> BranchCode { get; set; }
        public string flag { get; set; }
        public string SyncID { get; set; }
        public string CategoryID { get; set; }
        public Nullable<int> SubCatId { get; set; }
        public Nullable<int> SubSubCatId { get; set; }
        public Nullable<int> SubSubSubCatId { get; set; }
        public string orderstatus { get; set; }
        public string SystemVoucherNo { get; set; }
        public Nullable<decimal> value { get; set; }
        public Nullable<decimal> Taxable { get; set; }
        public string part_code { get; set; }
    }
}
