//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Svam.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class jwl_inventorystock
    {
        public int InvNO { get; set; }
        public string InvDate { get; set; }
        public string TransactionTypeCode { get; set; }
        public Nullable<int> challanamst_id { get; set; }
        public string material_id { get; set; }
        public string VoucherNo { get; set; }
        public string VoucherDate { get; set; }
        public string SKU { get; set; }
        public string ItemNM { get; set; }
        public string CentreName { get; set; }
        public string Unit { get; set; }
        public string BarcodeNo { get; set; }
        public Nullable<decimal> QuantityIn { get; set; }
        public Nullable<decimal> QuantityOut { get; set; }
        public Nullable<decimal> Rate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public int BranchCode { get; set; }
        public int CompanyId { get; set; }
        public string displayname { get; set; }
        public string RateType { get; set; }
        public string MakingCharge { get; set; }
        public string MakingChargeType { get; set; }
        public string ExtraCharge { get; set; }
        public string PcsSet { get; set; }
        public string ItemWeight { get; set; }
        public string ItemChargeName { get; set; }
        public string ItemType { get; set; }
        public string ItemPurity { get; set; }
        public string ExpiryDuration { get; set; }
        public string flag { get; set; }
        public string SyncID { get; set; }
    }
}
