//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Svam.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class jwl_itemsku
    {
        public int ID { get; set; }
        public string ItemName { get; set; }
        public string displayname { get; set; }
        public string SKU { get; set; }
        public string Barcode { get; set; }
        public string RateType { get; set; }
        public string MakingCharge { get; set; }
        public string MakingChargeType { get; set; }
        public string ExtraCharge { get; set; }
        public string PcsSet { get; set; }
        public string ItemWeight { get; set; }
        public string ItemChargeName { get; set; }
        public string ItemType { get; set; }
        public string ItemPurity { get; set; }
        public string ExpiryDuration { get; set; }
        public string GroupID { get; set; }
        public string DivID { get; set; }
        public string CategoryID { get; set; }
        public string ItemTypeID { get; set; }
        public string Photo { get; set; }
        public string ItemTypeCode { get; set; }
        public string BrandID { get; set; }
        public string ModelNo { get; set; }
        public string Active { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<double> BranchCode { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public byte[] product_image { get; set; }
        public string flag { get; set; }
        public string SyncID { get; set; }
    }
}
