//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Svam.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class jwl_addkarigar
    {
        public int ID { get; set; }
        public string KarigarID { get; set; }
        public string KarigarTypeID { get; set; }
        public string Karigar { get; set; }
        public string MobileNo { get; set; }
        public string TINNo { get; set; }
        public string Station_Centre { get; set; }
        public string groupCode { get; set; }
        public Nullable<float> openingbalance { get; set; }
        public string Address { get; set; }
        public Nullable<int> Country { get; set; }
        public Nullable<long> StateId { get; set; }
        public string City { get; set; }
        public string ZipCode { get; set; }
        public string PhoneNo { get; set; }
        public string CompanyID { get; set; }
        public string EmailID { get; set; }
        public string Website { get; set; }
        public string HeadOfficeAddress { get; set; }
        public string ContactName { get; set; }
        public string ContactMobile { get; set; }
        public string ContactDesignation { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string Remarks { get; set; }
        public string crdr { get; set; }
        public Nullable<int> branchCode { get; set; }
        public string flag { get; set; }
        public string SyncID { get; set; }
    }
}
