//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Svam.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class key
    {
        public int id { get; set; }
        public int user_id { get; set; }
        public string key1 { get; set; }
        public int level { get; set; }
        public bool ignore_limits { get; set; }
        public bool is_private_key { get; set; }
        public string ip_addresses { get; set; }
        public System.DateTime date_created { get; set; }
    }
}
