//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Svam.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class login_authentication
    {
        public int id { get; set; }
        public int login_id { get; set; }
        public string token { get; set; }
        public string expired_at { get; set; }
        public string created_at { get; set; }
        public string updated_at { get; set; }
        public string SyncID { get; set; }
    }
}
