//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Svam.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class login
    {
        public int Id { get; set; }
        public string UserNam { get; set; }
        public string Pass { get; set; }
        public string EDate { get; set; }
        public string Status { get; set; }
        public string SyncID { get; set; }
    }
}
