//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Svam.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class machine_rent
    {
        public int id { get; set; }
        public string machine_id { get; set; }
        public Nullable<int> allocate_id { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public string working { get; set; }
        public Nullable<decimal> daily_rent { get; set; }
        public string expence { get; set; }
        public string remarks { get; set; }
        public string tpi { get; set; }
        public string file { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> CompanyID { get; set; }
        public Nullable<int> BranchCode { get; set; }
        public string Flag { get; set; }
        public string SyncID { get; set; }
    }
}
