//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Svam.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class materialmasterexpens
    {
        public int id { get; set; }
        public string materialid { get; set; }
        public string Product_Name { get; set; }
        public string Quanity { get; set; }
        public string Item_to_produce { get; set; }
        public string Unit { get; set; }
        public string ExpHeadId { get; set; }
        public string ExpHeadName { get; set; }
        public string ExpQuamtity { get; set; }
        public string ExpUnitCost { get; set; }
        public string ExpTotalPrice { get; set; }
        public string ExpenseSubTotal { get; set; }
        public string Expenses { get; set; }
        public Nullable<int> CompanyID { get; set; }
        public Nullable<int> BranchCode { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string flag { get; set; }
        public string SyncID { get; set; }
    }
}
