//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Svam.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class menu_access
    {
        public int U_Roles_Id { get; set; }
        public string UserRolesName { get; set; }
        public string RollAssigned { get; set; }
        public string AssignDashboard { get; set; }
        public int CompanyId { get; set; }
        public int BranchCode { get; set; }
        public string CreatedBy { get; set; }
        public string ModifiedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string IsActive { get; set; }
        public string flag { get; set; }
        public string SyncID { get; set; }
    }
}
