//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Svam.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class multilabeldiscount
    {
        public int Id { get; set; }
        public string SKU { get; set; }
        public string VoucherNumber { get; set; }
        public string SystemvoucherNumber { get; set; }
        public string CustomerId { get; set; }
        public Nullable<decimal> PrimaryAmount { get; set; }
        public Nullable<decimal> MLD1 { get; set; }
        public Nullable<decimal> AmountMLD1 { get; set; }
        public Nullable<decimal> MLD2 { get; set; }
        public Nullable<decimal> AmountMLD2 { get; set; }
        public Nullable<decimal> MLD3 { get; set; }
        public Nullable<decimal> AmountMLD3 { get; set; }
        public int CompanyId { get; set; }
        public Nullable<int> BranchCode { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public string SyncID { get; set; }
        public string Flag { get; set; }
    }
}
