//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Svam.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class online_orders
    {
        public int order_id { get; set; }
        public string Item_Id { get; set; }
        public string Sku_ID { get; set; }
        public float PurchasePrice { get; set; }
        public float MRP { get; set; }
        public float MrpDiscount { get; set; }
        public float SavingAmt { get; set; }
        public Nullable<int> Item_qun { get; set; }
        public Nullable<int> Amount { get; set; }
        public string sales_type { get; set; }
        public Nullable<int> User_Id { get; set; }
        public Nullable<int> BranchCode { get; set; }
        public string CompanyID { get; set; }
        public string user_name { get; set; }
        public string user_email { get; set; }
        public Nullable<long> user_mobile { get; set; }
        public string user_address { get; set; }
        public string OrderId { get; set; }
        public string DeliveryDate { get; set; }
        public string DeliveryTime { get; set; }
        public Nullable<int> DeliveryCharge { get; set; }
        public string tracking_url { get; set; }
        public string Order_Status { get; set; }
        public string payment_type { get; set; }
        public string ratings { get; set; }
        public string review { get; set; }
        public string pro_images { get; set; }
        public int review_status { get; set; }
        public System.DateTime reviewDate { get; set; }
        public int voucherCode { get; set; }
        public string voucherType { get; set; }
        public string voucherVal { get; set; }
        public string CompletedDate { get; set; }
        public System.DateTime OrderDate { get; set; }
        public string isactive { get; set; }
        public int notificationStatus { get; set; }
        public string flag { get; set; }
        public string SyncID { get; set; }
        public Nullable<int> reason { get; set; }
        public string Unit { get; set; }
        public string ColorID { get; set; }
        public string SizeID { get; set; }
        public string AltUnit { get; set; }
        public int country { get; set; }
        public int state { get; set; }
        public int city { get; set; }
        public int pincode { get; set; }
        public string name { get; set; }
        public string mobile_no { get; set; }
        public string alt_mobile_no { get; set; }
        public string shipping_order_id { get; set; }
        public string shipment_id { get; set; }
        public string RefNo { get; set; }
        public string BillNo { get; set; }
        public Nullable<int> driver_id { get; set; }
        public string googleAddress { get; set; }
        public string latitude { get; set; }
        public string longitude { get; set; }
        public string shippedBy { get; set; }
        public string installmentType { get; set; }
        public string noOfInstallment { get; set; }
        public string totalNoOfInstallment { get; set; }
        public string processingFee { get; set; }
        public string fileCharge { get; set; }
        public string interestPer { get; set; }
        public string downPayment { get; set; }
    }
}
