//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Svam.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class online_cancel_orders
    {
        public int order_id { get; set; }
        public string Item_id { get; set; }
        public string Sku_ID { get; set; }
        public Nullable<float> PurchasePrice { get; set; }
        public float MRP { get; set; }
        public float MrpDiscount { get; set; }
        public float SavingAmt { get; set; }
        public Nullable<int> Item_qun { get; set; }
        public Nullable<int> Amount { get; set; }
        public string sales_type { get; set; }
        public Nullable<int> User_Id { get; set; }
        public Nullable<int> BranchCode { get; set; }
        public string CompanyID { get; set; }
        public string user_name { get; set; }
        public string user_email { get; set; }
        public Nullable<long> user_mobile { get; set; }
        public string user_address { get; set; }
        public string OrderId { get; set; }
        public string DeliveryDate { get; set; }
        public string DeliveryTime { get; set; }
        public Nullable<int> DeliveryCharge { get; set; }
        public string Order_Status { get; set; }
        public string payment_type { get; set; }
        public string ratings { get; set; }
        public string review { get; set; }
        public int review_status { get; set; }
        public System.DateTime reviewDate { get; set; }
        public int voucherCode { get; set; }
        public string voucherType { get; set; }
        public string voucherVal { get; set; }
        public string CompletedDate { get; set; }
        public System.DateTime OrderDate { get; set; }
        public string isactive { get; set; }
        public string flag { get; set; }
        public int reason { get; set; }
        public string SyncID { get; set; }
        public string shippedBy { get; set; }
    }
}
