//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Svam.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class orders_amazone
    {
        public int ID { get; set; }
        public string AmazonOrderID { get; set; }
        public string OrderType { get; set; }
        public string PurchaseDate { get; set; }
        public string BuyerEmail { get; set; }
        public string IsReplacementOrder { get; set; }
        public string LastUpdateDate { get; set; }
        public string NumberOfItemsShipped { get; set; }
        public string ShipServiceLevel { get; set; }
        public string OrderStatus { get; set; }
        public string SalesChannel { get; set; }
        public string IsBusinessOrder { get; set; }
        public string NumberOfItemsUnshipped { get; set; }
        public string PaymentMethodDetail { get; set; }
        public string BuyerName { get; set; }
        public string CurrencyCode { get; set; }
        public string OrderAmount { get; set; }
        public string IsPremiumOrder { get; set; }
        public string EarliestShipDate { get; set; }
        public string FulfillmentChannel { get; set; }
        public string PaymentMethod { get; set; }
        public string ShippingAddressCity { get; set; }
        public string ShippingAddressPostalCode { get; set; }
        public string ShippingAddressState { get; set; }
        public string ShippingAddressCountryCode { get; set; }
        public string ShippingAddressName { get; set; }
        public string ShippingAddress1 { get; set; }
        public string ShippingAddress2 { get; set; }
        public string IsPrime { get; set; }
        public string ShipmentServiceLevelCategory { get; set; }
        public long CompanyId { get; set; }
        public long BranchCode { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string IsActive { get; set; }
        public string SyncID { get; set; }
        public string flag { get; set; }
    }
}
