//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Svam.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class payment_gateways
    {
        public int id { get; set; }
        public string gatwayName { get; set; }
        public string salt_key { get; set; }
        public string marchent_key { get; set; }
        public string merchant_id { get; set; }
        public string upi_id { get; set; }
        public int company_id { get; set; }
        public int status { get; set; }
        public string mode { get; set; }
        public System.DateTime created { get; set; }
    }
}
