//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Svam.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class product
    {
        public int product_id { get; set; }
        public string product_name { get; set; }
        public string product_brand { get; set; }
        public decimal product_price { get; set; }
        public string product_ram { get; set; }
        public string product_storage { get; set; }
        public string product_camera { get; set; }
        public string product_image { get; set; }
        public int product_quantity { get; set; }
        public string product_status { get; set; }
    }
}
