//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Svam.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class pur_purchasegoodsreceived
    {
        public int ID { get; set; }
        public string GRN { get; set; }
        public System.DateTime GRNDt { get; set; }
        public string purchase_type { get; set; }
        public string PurchaseOrderNo { get; set; }
        public Nullable<System.DateTime> PurchaseOrderDate { get; set; }
        public string SupplierNM { get; set; }
        public string SupplierCode { get; set; }
        public string MobileNo { get; set; }
        public string Department { get; set; }
        public string Division { get; set; }
        public string Location { get; set; }
        public Nullable<System.DateTime> DueDt { get; set; }
        public string ReferenceNo { get; set; }
        public string ReferenceDate { get; set; }
        public string Particulars { get; set; }
        public string Terms { get; set; }
        public string ShipAdd { get; set; }
        public string TransporterNm { get; set; }
        public string LorryNo { get; set; }
        public Nullable<decimal> Total { get; set; }
        public Nullable<decimal> Balance { get; set; }
        public Nullable<decimal> ItemTotal { get; set; }
        public Nullable<decimal> TDisPer { get; set; }
        public Nullable<decimal> TDIsAmt { get; set; }
        public Nullable<decimal> TSubTotal { get; set; }
        public Nullable<decimal> TSerTper { get; set; }
        public Nullable<decimal> TSerTTotal { get; set; }
        public Nullable<decimal> TEDPer { get; set; }
        public Nullable<decimal> TEDAmt { get; set; }
        public Nullable<decimal> TVATPer { get; set; }
        public Nullable<decimal> TVATAmt { get; set; }
        public Nullable<decimal> TSATPer { get; set; }
        public Nullable<decimal> TSATAmt { get; set; }
        public Nullable<decimal> PackagingCharges { get; set; }
        public Nullable<decimal> DeliveryCharges { get; set; }
        public Nullable<decimal> Adjustment { get; set; }
        public string Rounding { get; set; }
        public Nullable<decimal> GrandTotal { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public int CustID { get; set; }
        public int branch { get; set; }
        public Nullable<int> TermID { get; set; }
        public int CompanyId { get; set; }
        public string Saved { get; set; }
        public string Paymode { get; set; }
        public string ChequeNo { get; set; }
        public string NameOnCard { get; set; }
        public string CardNumber { get; set; }
        public string BankName { get; set; }
        public Nullable<float> PayAmount { get; set; }
        public string DelieveryPlace { get; set; }
        public string Remarks { get; set; }
        public string Accpost { get; set; }
        public string StatusCode { get; set; }
        public string ReturnSt { get; set; }
        public string AccountName { get; set; }
        public Nullable<int> AccountNumber { get; set; }
        public string TINNo { get; set; }
        public string Address { get; set; }
        public string EmailID { get; set; }
        public string IsActive { get; set; }
        public string InvoiceStatus { get; set; }
        public string flag { get; set; }
        public string SyncID { get; set; }
        public Nullable<float> TcsAmount { get; set; }
        public string AditionalTax { get; set; }
        public Nullable<decimal> TaxPer { get; set; }
        public Nullable<decimal> AditionalTaxAmt { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<decimal> freight_charges { get; set; }
        public Nullable<decimal> freight_charges_gst_per { get; set; }
        public Nullable<decimal> packing_charges { get; set; }
        public Nullable<decimal> packing_charges_gst_per { get; set; }
        public Nullable<decimal> forwarding_charges { get; set; }
        public Nullable<decimal> forwarding_charges_gst_per { get; set; }
        public Nullable<decimal> other_charges { get; set; }
        public Nullable<decimal> other_charges_gst_per { get; set; }
        public string purchase_bill_type { get; set; }
        public string bill_type { get; set; }
        public Nullable<decimal> insurance_charges { get; set; }
        public Nullable<decimal> insurance_charges_gst_per { get; set; }
        public Nullable<decimal> tot_gst { get; set; }
        public Nullable<decimal> DiscountPer { get; set; }
        public string purchaseby { get; set; }
    }
}
