//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Svam.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class pur_prline
    {
        public int ID { get; set; }
        public string PrNo { get; set; }
        public string SKU { get; set; }
        public string Description { get; set; }
        public decimal Qty { get; set; }
        public string Unit { get; set; }
        public decimal UnitPrice { get; set; }
        public Nullable<decimal> LineSubTotal { get; set; }
        public string CreatedBy { get; set; }
        public string CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public string ModifiedDate { get; set; }
        public int BranchCode { get; set; }
        public string companyId { get; set; }
        public string reqdata { get; set; }
        public string remarks { get; set; }
        public string SyncID { get; set; }
    }
}
