//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Svam.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class pur_purchaseordertypes
    {
        public string POTypeCode { get; set; }
        public string PurchaseOrderType { get; set; }
        public string Description { get; set; }
        public string Default { get; set; }
        public string PrintAutomatically { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public string DefaultDefault { get; set; }
        public string PrintAutomaticallyDefault { get; set; }
        public int BranchCode { get; set; }
        public string Active { get; set; }
        public string ActiveDefault { get; set; }
        public string SyncID { get; set; }
    }
}
