//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Svam.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class pur_suppliers_backup11sep
    {
        public int ID { get; set; }
        public string SupplierID { get; set; }
        public string SupplierTypeID { get; set; }
        public string Supplier { get; set; }
        public string MobileNo { get; set; }
        public string TINNo { get; set; }
        public decimal CreditLimit { get; set; }
        public string Address { get; set; }
        public Nullable<long> StateId { get; set; }
        public string City { get; set; }
        public string ZipCode { get; set; }
        public string PhoneNo { get; set; }
        public string FaxNo { get; set; }
        public string EmailID { get; set; }
        public string Website { get; set; }
        public string HeadOfficeAddress { get; set; }
        public string ContactName { get; set; }
        public string ContactMobile { get; set; }
        public string ContactDesignation { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public string Remarks { get; set; }
        public string AadharNo { get; set; }
        public string PANNo { get; set; }
        public string crdr { get; set; }
        public Nullable<int> branch { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public Nullable<int> CustID { get; set; }
        public string IsActive { get; set; }
        public string SyncID { get; set; }
    }
}
