//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Svam.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class pur_return
    {
        public int ID { get; set; }
        public string ReturnNo { get; set; }
        public System.DateTime ReturnNoDt { get; set; }
        public string GRN { get; set; }
        public System.DateTime GRNDt { get; set; }
        public string SupplierNM { get; set; }
        public string SupplierCode { get; set; }
        public string MobileNo { get; set; }
        public string POType { get; set; }
        public string Department { get; set; }
        public string Division { get; set; }
        public string Location { get; set; }
        public Nullable<System.DateTime> DueDt { get; set; }
        public string Particulars { get; set; }
        public string TerBill { get; set; }
        public Nullable<decimal> Total { get; set; }
        public Nullable<decimal> Balance { get; set; }
        public Nullable<decimal> ItemTotal { get; set; }
        public Nullable<decimal> Adjusted { get; set; }
        public Nullable<decimal> TDisPer { get; set; }
        public Nullable<decimal> TDIsAmt { get; set; }
        public Nullable<decimal> TSubTotal { get; set; }
        public Nullable<decimal> TSerTper { get; set; }
        public Nullable<decimal> TSerTTotal { get; set; }
        public Nullable<decimal> TEDPer { get; set; }
        public Nullable<decimal> TEDAmt { get; set; }
        public Nullable<decimal> TVATPer { get; set; }
        public Nullable<decimal> TVATAmt { get; set; }
        public Nullable<decimal> TSATPer { get; set; }
        public Nullable<decimal> TSATAmt { get; set; }
        public Nullable<decimal> PackagingCharges { get; set; }
        public Nullable<decimal> DeliveryCharges { get; set; }
        public Nullable<decimal> Adjustment { get; set; }
        public string Rounding { get; set; }
        public Nullable<decimal> GrandTotal { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public Nullable<int> TermID { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public int branch { get; set; }
        public string Remarks { get; set; }
        public string Saved { get; set; }
        public string Paymode { get; set; }
        public string Accpost { get; set; }
        public string StatusCode { get; set; }
        public string TINNo { get; set; }
        public string Address { get; set; }
        public string EmailID { get; set; }
        public string flag { get; set; }
        public string SyncID { get; set; }
        public string GSTType { get; set; }
        public Nullable<int> POS { get; set; }
        public Nullable<int> status { get; set; }
    }
}
