//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Svam.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class pur_pr
    {
        public int ID { get; set; }
        public string PrNo { get; set; }
        public Nullable<System.DateTime> PrDate { get; set; }
        public string SupplierNM { get; set; }
        public string SupplierCode { get; set; }
        public string MobileNo { get; set; }
        public Nullable<decimal> Total { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public string StatusCode { get; set; }
        public Nullable<int> BranchCode { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public string requestto { get; set; }
        public string SyncID { get; set; }
    }
}
