//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Svam.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class purchase_order_setting
    {
        public int ID { get; set; }
        public string SupplierName { get; set; }
        public string MobileNo { get; set; }
        public string BillNo { get; set; }
        public string BillDate { get; set; }
        public string ExpectedDate { get; set; }
        public string Barcode { get; set; }
        public string ItemName { get; set; }
        public string Unit { get; set; }
        public string Color { get; set; }
        public string Size { get; set; }
        public string Qty { get; set; }
        public string Price { get; set; }
        public string Total { get; set; }
        public string UnitType { get; set; }
        public string Amount { get; set; }
        public string TotalTax { get; set; }
        public string GrandTotal { get; set; }
        public string CompanyID { get; set; }
        public string BranchCode { get; set; }
        public string createdBy { get; set; }
        public string createdDate { get; set; }
        public string modifiedBy { get; set; }
        public Nullable<System.DateTime> modifiedDate { get; set; }
        public string SyncID { get; set; }
        public string flag { get; set; }
    }
}
