//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Svam.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class purchase_setting
    {
        public int ID { get; set; }
        public string PurchaseType { get; set; }
        public string Supplier { get; set; }
        public string SupInvNo { get; set; }
        public string SupInvDate { get; set; }
        public string MobileNo { get; set; }
        public string BillNo { get; set; }
        public string BillDate { get; set; }
        public string Pos { get; set; }
        public string ItemCentre { get; set; }
        public string Search { get; set; }
        public string SerialNo { get; set; }
        public string Barcode { get; set; }
        public string Unit { get; set; }
        public string AltUnit { get; set; }
        public string Color { get; set; }
        public string Size { get; set; }
        public string Qty { get; set; }
        public string Price { get; set; }
        public string Total { get; set; }
        public string RackNo { get; set; }
        public string ExpireDate { get; set; }
        public string ItemName { get; set; }
        public string UnitType { get; set; }
        public string MRP { get; set; }
        public string ComDisc { get; set; }
        public string BP { get; set; }
        public string PRDiscount { get; set; }
        public string SCDiscount { get; set; }
        public string LDDiscount { get; set; }
        public string EXDiscount { get; set; }
        public string PRRate { get; set; }
        public string TaxableAmount { get; set; }
        public string TotalAmount { get; set; }
        public string MRPDiscount { get; set; }
        public string PayMode { get; set; }
        public string RefNo { get; set; }
        public string RefDate { get; set; }
        public string TotalQty { get; set; }
        public string TotalTax { get; set; }
        public string GrandTotal { get; set; }
        public string AdvPaid { get; set; }
        public string ReceivedAmt { get; set; }
        public string BalAmt { get; set; }
        public string Discount { get; set; }
        public string ManufacturingDate { get; set; }
        public string Validity { get; set; }
        public string Deal { get; set; }
        public string CompanyID { get; set; }
        public string BranchCode { get; set; }
        public string createdBy { get; set; }
        public string createdDate { get; set; }
        public string modifiedBy { get; set; }
        public Nullable<System.DateTime> modifiedDate { get; set; }
        public string SyncID { get; set; }
        public string flag { get; set; }
    }
}
