//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Svam.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class refrel_points
    {
        public int id { get; set; }
        public string refrel_for { get; set; }
        public int points { get; set; }
        public string amount { get; set; }
        public System.DateTime valid_till { get; set; }
        public string type { get; set; }
        public string offline { get; set; }
        public string for_company { get; set; }
        public string CompanyID { get; set; }
        public string branch { get; set; }
        public int status { get; set; }
        public string flag { get; set; }
        public string SyncID { get; set; }
        public Nullable<int> BranchCode { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    }
}
