//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Svam.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class refunditem
    {
        public int ID { get; set; }
        public string AmazonOrderID { get; set; }
        public string PostedDate { get; set; }
        public string CommissionFeeAmount { get; set; }
        public string CommissionFeeCode { get; set; }
        public string RefundCommissionFeeAmount { get; set; }
        public string RefundCommissionFeeCode { get; set; }
        public string PromotionCurrencyAmount1 { get; set; }
        public string PromotionId1 { get; set; }
        public string PromotionCurrencyAmount2 { get; set; }
        public string PromotionId2 { get; set; }
        public string OrderAdjustmentItemId { get; set; }
        public string QuantityShipped { get; set; }
        public string ChargeType1 { get; set; }
        public string ChargeAmount1 { get; set; }
        public string ChargeCurrencyCode1 { get; set; }
        public string ChargeType2 { get; set; }
        public string ChargeAmount2 { get; set; }
        public string ChargeCurrencyCode2 { get; set; }
        public string ChargeType3 { get; set; }
        public string ChargeAmount3 { get; set; }
        public string ChargeCurrencyCode3 { get; set; }
        public string ChargeType4 { get; set; }
        public string ChargeAmount4 { get; set; }
        public string ChargeCurrencyCode4 { get; set; }
        public string SellerSKU { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string IsActive { get; set; }
        public string SyncID { get; set; }
        public string flag { get; set; }
    }
}
