//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Svam.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class registration
    {
        public int id { get; set; }
        public string user_name { get; set; }
        public string contact_no { get; set; }
        public string alt_contact_no { get; set; }
        public string email { get; set; }
        public string company_id { get; set; }
        public string gstin_no { get; set; }
        public Nullable<int> state_id { get; set; }
        public Nullable<int> city_id { get; set; }
        public string pincode { get; set; }
        public string type { get; set; }
        public string address { get; set; }
        public string adharcard { get; set; }
        public string pancard { get; set; }
        public string cheque { get; set; }
        public string photo { get; set; }
        public string declaration { get; set; }
        public string bankDetails { get; set; }
        public string description { get; set; }
        public string status { get; set; }
        public string registerBy_code { get; set; }
        public string reseller_code { get; set; }
        public string created_by { get; set; }
        public string updated_by { get; set; }
        public System.DateTime updated_date { get; set; }
        public string created_date { get; set; }
        public string sync_id { get; set; }
        public string flag { get; set; }
        public Nullable<int> BranchCode { get; set; }
    }
}
