//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Svam.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class sal_transferouts
    {
        public int ID { get; set; }
        public System.DateTime TransferOrderDate { get; set; }
        public int ShipBranchCode { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public Nullable<decimal> SubTotal { get; set; }
        public Nullable<decimal> ItemTax { get; set; }
        public Nullable<decimal> PackagingCharges { get; set; }
        public Nullable<decimal> DeliveryCharges { get; set; }
        public Nullable<decimal> ItemDiscount { get; set; }
        public Nullable<decimal> DiscountOnTotal { get; set; }
        public Nullable<decimal> Adjustment { get; set; }
        public Nullable<decimal> Rounding { get; set; }
        public Nullable<decimal> NetReceivable { get; set; }
        public Nullable<decimal> NetReceived { get; set; }
        public Nullable<decimal> CurrentDue { get; set; }
        public string Particulars { get; set; }
        public Nullable<int> Document { get; set; }
        public Nullable<int> TermID { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public int BranchCode { get; set; }
        public int TransferOrderNo { get; set; }
        public Nullable<int> PurchaseOrderNo { get; set; }
        public string SyncID { get; set; }
        public string flag { get; set; }
    }
}
