//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Svam.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class sal_salesorderdeliveries
    {
        public int ID { get; set; }
        public string Area { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public string VehicleNo { get; set; }
        public System.DateTime ScheduleDateTime { get; set; }
        public Nullable<System.TimeSpan> StartTime { get; set; }
        public Nullable<System.TimeSpan> EndTime { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> Document { get; set; }
        public string StatusCode { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public Nullable<int> TermID { get; set; }
        public int BranchCode { get; set; }
        public int DeliveryID { get; set; }
        public string SyncID { get; set; }
        public string flag { get; set; }
    }
}
