//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Svam.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class sal_salesordertypes
    {
        public string SOTypeCode { get; set; }
        public string SalesOrderType { get; set; }
        public string Description { get; set; }
        public string Default { get; set; }
        public string DefaultDefault { get; set; }
        public string PrintAutomatically { get; set; }
        public Nullable<decimal> PackagingCharges { get; set; }
        public string PackagingChargesFixed { get; set; }
        public Nullable<decimal> DeliveryCharges { get; set; }
        public string DeliveryChargesFixed { get; set; }
        public string PrintKOT { get; set; }
        public string PrintKOTDefault { get; set; }
        public Nullable<int> NoOfInvoicePrint { get; set; }
        public Nullable<int> NoOfKOTPrint { get; set; }
        public string InvoicePrintOnSave { get; set; }
        public string DeliveryTimeMandatory { get; set; }
        public string DeliveryTimeMandatoryDefault { get; set; }
        public string Active { get; set; }
        public string ActiveDefault { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public int BranchCode { get; set; }
        public Nullable<int> TaxID1 { get; set; }
        public Nullable<int> TaxID2 { get; set; }
        public Nullable<int> TaxID3 { get; set; }
        public Nullable<int> Discount1 { get; set; }
        public Nullable<int> Discount2 { get; set; }
        public Nullable<int> Discount3 { get; set; }
        public string TemplateCode { get; set; }
        public string InvoicePrinter { get; set; }
        public string KOTPrinter { get; set; }
        public string SyncID { get; set; }
        public string flag { get; set; }
    }
}
