//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Svam.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class sal_paymentmode
    {
        public int id { get; set; }
        public string SONO { get; set; }
        public string PaymentMode { get; set; }
        public Nullable<decimal> Transactionamt { get; set; }
        public Nullable<decimal> paymentAmountOthers { get; set; }
        public Nullable<decimal> paymentModeCash { get; set; }
        public Nullable<decimal> paymentAmountCash { get; set; }
        public Nullable<decimal> Bankchrgs { get; set; }
        public string Particular { get; set; }
        public Nullable<System.DateTime> Dt { get; set; }
        public string BankNm { get; set; }
        public string BranchNm { get; set; }
        public string CardType { get; set; }
        public string CardTransactionNo { get; set; }
        public Nullable<System.DateTime> E1 { get; set; }
        public string E2 { get; set; }
        public string E3 { get; set; }
        public string E4 { get; set; }
        public Nullable<int> branch { get; set; }
        public string CompanyID { get; set; }
        public string SyncID { get; set; }
        public string flag { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public string CreatedBy { get; set; }
        public string ModifiedBy { get; set; }
        public string SystemVoucherNo { get; set; }
    }
}
