//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Svam.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class sal_returninwards
    {
        public int ID { get; set; }
        public Nullable<int> challanamst_id { get; set; }
        public Nullable<int> sal_returninwardlines_ID { get; set; }
        public Nullable<int> customers_ID { get; set; }
        public string ReturnInwardNo { get; set; }
        public System.DateTime ReturnInwardDate { get; set; }
        public string StatusCode { get; set; }
        public string SalesOrderNo { get; set; }
        public string SalesOrderDate { get; set; }
        public string CustomerNm { get; set; }
        public string CustomerID { get; set; }
        public string ReturnAll { get; set; }
        public string Particulars { get; set; }
        public string Term { get; set; }
        public Nullable<int> TermID { get; set; }
        public Nullable<decimal> Total { get; set; }
        public Nullable<decimal> CurrentDue { get; set; }
        public Nullable<decimal> ItemTotal { get; set; }
        public Nullable<long> DisPer { get; set; }
        public Nullable<decimal> DisAmt { get; set; }
        public Nullable<decimal> SubTotal { get; set; }
        public Nullable<long> ServiceTaxPer { get; set; }
        public Nullable<decimal> ServiceTaxAmt { get; set; }
        public Nullable<long> VATPer { get; set; }
        public Nullable<decimal> VATAmt { get; set; }
        public Nullable<long> SATPer { get; set; }
        public Nullable<decimal> SATAmt { get; set; }
        public Nullable<decimal> Rounding { get; set; }
        public Nullable<decimal> GrandTotal { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public int BranchCode { get; set; }
        public string CompanyID { get; set; }
        public string CreditNo { get; set; }
        public string CreditDt { get; set; }
        public string flag { get; set; }
        public string SyncID { get; set; }
        public string pincode { get; set; }
        public string GSTType { get; set; }
        public string MobileNo { get; set; }
        public string Address { get; set; }
        public Nullable<int> POS { get; set; }
        public string Remarks { get; set; }
        public string EntryType { get; set; }
        public Nullable<int> status { get; set; }
        public string ReturnType { get; set; }
        public Nullable<decimal> Adjusted { get; set; }
    }
}
