//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Svam.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class sal_unsaveddatamisuse
    {
        public int ID { get; set; }
        public int SalesOrderNo { get; set; }
        public string SKU { get; set; }
        public string Description { get; set; }
        public decimal UnitPrice { get; set; }
        public decimal Quantity { get; set; }
        public decimal LinePrice { get; set; }
        public Nullable<decimal> LineTax { get; set; }
        public Nullable<int> DiscountRuleID { get; set; }
        public Nullable<decimal> LineDiscount { get; set; }
        public Nullable<int> DiscountSalesOrderLineID { get; set; }
        public Nullable<decimal> ExtendedPrice { get; set; }
        public string StatusCode { get; set; }
        public Nullable<System.DateTime> ItemDeliveryDate { get; set; }
        public string UpdatedInStock { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public Nullable<int> KOT { get; set; }
        public int BranchCode { get; set; }
        public string Unit { get; set; }
        public Nullable<decimal> TaxRate { get; set; }
        public Nullable<int> TaxAccountNumber { get; set; }
        public string Instructions { get; set; }
        public int SalesOrderLineID { get; set; }
        public Nullable<decimal> PreparationTime { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public string SyncID { get; set; }
        public string flag { get; set; }
    }
}
