//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Svam.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class sal_discountrules
    {
        public int ID { get; set; }
        public string DiscountName { get; set; }
        public Nullable<decimal> SalesQuantity { get; set; }
        public string SKU { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public Nullable<decimal> FixedAmount { get; set; }
        public Nullable<decimal> Percentage { get; set; }
        public string Active { get; set; }
        public string Description { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public Nullable<int> BranchCode { get; set; }
        public string RuleType { get; set; }
        public Nullable<decimal> MinimumInvoiceAmount { get; set; }
        public Nullable<decimal> MaximumInvoiceAmount { get; set; }
        public Nullable<int> DiscountRuleID { get; set; }
        public string SyncID { get; set; }
        public string flag { get; set; }
    }
}
