//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Svam.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class sale_finance
    {
        public int ID { get; set; }
        public string financer { get; set; }
        public string approval_no { get; set; }
        public Nullable<decimal> initial_amount { get; set; }
        public Nullable<decimal> total_amount { get; set; }
        public Nullable<decimal> received_amt { get; set; }
        public Nullable<decimal> bal_amt { get; set; }
        public string customer_name { get; set; }
        public string customers_ID { get; set; }
        public string challan_no { get; set; }
        public Nullable<System.DateTime> ChalanDt { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> CompanyID { get; set; }
        public Nullable<int> BranchCode { get; set; }
        public string Flag { get; set; }
        public string SyncID { get; set; }
    }
}
