//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Svam.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class sales_order_setting
    {
        public int ID { get; set; }
        public string MobileNo { get; set; }
        public string CustName { get; set; }
        public string Address { get; set; }
        public string Pos { get; set; }
        public string SaleType { get; set; }
        public string BillNo { get; set; }
        public string BillDate { get; set; }
        public string DeliveryDate { get; set; }
        public string SrchBillNo { get; set; }
        public string Credit { get; set; }
        public string ZipCode { get; set; }
        public string ItemName { get; set; }
        public string Unit { get; set; }
        public string AltUnit { get; set; }
        public string Color { get; set; }
        public string Size { get; set; }
        public string CurrentStk { get; set; }
        public string ItemCode { get; set; }
        public string Qty { get; set; }
        public string OurPrice { get; set; }
        public string MRP { get; set; }
        public string DiscPer { get; set; }
        public string DiscAmt { get; set; }
        public string AmountAfterDiscount { get; set; }
        public string TaxableAmount { get; set; }
        public string PayMode { get; set; }
        public string RefNo { get; set; }
        public string Amount { get; set; }
        public string PaymentDet { get; set; }
        public string TaxDet { get; set; }
        public string TotQty { get; set; }
        public string TotAmt { get; set; }
        public string ExtDisc { get; set; }
        public string Discount { get; set; }
        public string TotGst { get; set; }
        public string TotTax { get; set; }
        public string Receivable { get; set; }
        public string BalAmt { get; set; }
        public string Received { get; set; }
        public string Retrn { get; set; }
        public string GrandTot { get; set; }
        public string CompanyID { get; set; }
        public string BranchCode { get; set; }
        public string createdBy { get; set; }
        public string createdDate { get; set; }
        public string modifiedBy { get; set; }
        public Nullable<System.DateTime> modifiedDate { get; set; }
        public string SyncID { get; set; }
        public string flag { get; set; }
    }
}
