//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Svam.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class sale_finance_details
    {
        public int ID { get; set; }
        public int sale_finance_id { get; set; }
        public string receipt_type { get; set; }
        public string challan_no { get; set; }
        public string rv_no { get; set; }
        public string payment_mode { get; set; }
        public string slip_no { get; set; }
        public Nullable<decimal> amount { get; set; }
        public string notes { get; set; }
        public string demand_draft_no { get; set; }
        public string card_account { get; set; }
        public string card_holder_bank { get; set; }
        public string no_of_emis { get; set; }
        public string emi_approval_no { get; set; }
        public string card_no { get; set; }
        public string bank_location { get; set; }
        public Nullable<System.DateTime> cheque_date { get; set; }
        public string cheque_no { get; set; }
        public Nullable<System.DateTime> txn_date { get; set; }
        public string txn_no { get; set; }
        public string wallet_account { get; set; }
        public string ref_no { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> CompanyID { get; set; }
        public Nullable<int> BranchCode { get; set; }
        public string Flag { get; set; }
        public string SyncID { get; set; }
    }
}
