//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Svam.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class saleprice
    {
        public int Id { get; set; }
        public string SKU { get; set; }
        public Nullable<decimal> PurPrice { get; set; }
        public Nullable<decimal> Margin { get; set; }
        public Nullable<decimal> SalePrice1 { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<long> CompanyId { get; set; }
        public Nullable<int> BranchCode { get; set; }
        public string Loc { get; set; }
        public Nullable<decimal> MRP { get; set; }
        public string flag { get; set; }
        public string SyncID { get; set; }
    }
}
