//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Svam.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class social_signin
    {
        public int id { get; set; }
        public string signin_type { get; set; }
        public string appId { get; set; }
        public string version { get; set; }
        public string CompanyID { get; set; }
        public string SyncID { get; set; }
        public int status { get; set; }
        public string flag { get; set; }
    }
}
