//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Svam.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class sr_tablereservations
    {
        public int ID { get; set; }
        public string ReservationID { get; set; }
        public string BookingDate { get; set; }
        public string ReservationType { get; set; }
        public string Customer { get; set; }
        public string ReservationDate { get; set; }
        public Nullable<System.TimeSpan> ReservationTm { get; set; }
        public string TT { get; set; }
        public Nullable<int> NoOfGuests { get; set; }
        public string TableNo { get; set; }
        public string StatusCode { get; set; }
        public string Remark { get; set; }
        public string CreatedBy { get; set; }
        public string CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public string ModifiedDate { get; set; }
        public int BranchCode { get; set; }
        public string SyncID { get; set; }
        public string flag { get; set; }
    }
}
