//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Svam.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class subscriptions_level
    {
        public int SID { get; set; }
        public string LevelName { get; set; }
        public string LevelType { get; set; }
        public string Description { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<decimal> MainPrice { get; set; }
        public Nullable<decimal> GST { get; set; }
        public string Status { get; set; }
        public string planType { get; set; }
        public string CurrencyType { get; set; }
        public string SyncID { get; set; }
        public string flag { get; set; }
    }
}
