//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Svam.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class subscription_cart
    {
        public int ID { get; set; }
        public string planid { get; set; }
        public string price { get; set; }
        public Nullable<decimal> GST { get; set; }
        public string discount { get; set; }
        public string CompanyID { get; set; }
        public string BranchCode { get; set; }
        public string qty { get; set; }
        public string ip_address { get; set; }
        public string plan_name { get; set; }
    }
}
