//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Svam.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class supplierpayinfo
    {
        public int id { get; set; }
        public Nullable<int> PaymentSlipId { get; set; }
        public string VoucherNo { get; set; }
        public Nullable<System.DateTime> VoucherDt { get; set; }
        public string SupplierName { get; set; }
        public string SupplierCode { get; set; }
        public Nullable<decimal> TenderAmt { get; set; }
        public Nullable<int> Cash { get; set; }
        public Nullable<decimal> CashAmt { get; set; }
        public Nullable<int> CheQueDD { get; set; }
        public Nullable<decimal> ChequeDDAmt { get; set; }
        public string ChequeDetails { get; set; }
        public Nullable<System.DateTime> ChequeDt { get; set; }
        public string BankCode { get; set; }
        public string CheckBankNm { get; set; }
        public string IfscCode { get; set; }
        public string OtherBNkCode { get; set; }
        public Nullable<int> CreditCard { get; set; }
        public Nullable<decimal> CreditCardAmt { get; set; }
        public string NameOnCredit { get; set; }
        public string CreditCardNo { get; set; }
        public Nullable<int> DebitCard { get; set; }
        public Nullable<decimal> DebitCardAmt { get; set; }
        public string NameOnDebitCard { get; set; }
        public string DebitCardNo { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<decimal> openingbalance { get; set; }
        public Nullable<decimal> closingbalance { get; set; }
        public Nullable<decimal> AdjustedAmt { get; set; }
        public string branch { get; set; }
        public string CompanyId { get; set; }
        public string flag { get; set; }
        public string SyncID { get; set; }
    }
}
