//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Svam.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_userlogin
    {
        public int user_id { get; set; }
        public string user_name { get; set; }
        public string user_email { get; set; }
        public Nullable<long> user_mobile { get; set; }
        public string user_password { get; set; }
        public string userType { get; set; }
        public string userCode { get; set; }
        public string token { get; set; }
        public string user_address { get; set; }
        public string cust_id { get; set; }
        public string last_login { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string IsActive { get; set; }
        public string CompanyID { get; set; }
        public string flag { get; set; }
        public string SyncID { get; set; }
        public string KeyVersion { get; set; }
        public string shipping_preference { get; set; }
        public string shipping_group { get; set; }
    }
}
