//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Svam.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_year_of_operation
    {
        public int Year_ID { get; set; }
        public string Default_Year { get; set; }
        public string From_Year { get; set; }
        public string To_Year { get; set; }
        public string Full_Name { get; set; }
        public string Designation { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string State_Province { get; set; }
        public string Country_Name { get; set; }
        public string Pin_Code { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string flag { get; set; }
        public string SyncID { get; set; }
        public Nullable<long> BranchCode { get; set; }
        public Nullable<long> CompanyId { get; set; }
    }
}
