//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Svam.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_useraddress
    {
        public int id { get; set; }
        public string address { get; set; }
        public int country { get; set; }
        public int state { get; set; }
        public int city { get; set; }
        public int pincode { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public string user_id { get; set; }
        public string Name_ { get; set; }
        public string mobileno { get; set; }
        public string alt_mobileno { get; set; }
        public string address_type { get; set; }
        public string googleAddress { get; set; }
        public string lat { get; set; }
        public string @long { get; set; }
        public Nullable<System.DateTime> createdDate { get; set; }
        public string CreatedBy { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string BranchCode { get; set; }
        public string flag { get; set; }
        public string SyncId { get; set; }
    }
}
