//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Svam.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_productattribute
    {
        public int id { get; set; }
        public Nullable<int> pid { get; set; }
        public string categoryid { get; set; }
        public Nullable<int> subcategoryid { get; set; }
        public Nullable<int> subsubcategoryid { get; set; }
        public Nullable<int> brandid { get; set; }
        public Nullable<int> groupid { get; set; }
        public Nullable<int> attributeid { get; set; }
        public string attribuitelbltext { get; set; }
        public string Name { get; set; }
        public string SKU { get; set; }
        public string HSN { get; set; }
        public string MRP { get; set; }
        public string SellingPrice { get; set; }
        public Nullable<int> IsActive { get; set; }
        public string isStkShow { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> CompanyID { get; set; }
        public Nullable<int> BranchCode { get; set; }
        public string flag { get; set; }
        public string SyncID { get; set; }
        public string item_id { get; set; }
        public string tab_num { get; set; }
    }
}
