//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Svam.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_selling_product
    {
        public int id { get; set; }
        public string item_id { get; set; }
        public string title { get; set; }
        public int isChecked { get; set; }
        public string company_id { get; set; }
        public string branch_id { get; set; }
        public string flag { get; set; }
        public string SyncID { get; set; }
    }
}
