//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Svam.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_report_setting
    {
        public int userid { get; set; }
        public int companyid { get; set; }
        public int branch { get; set; }
        public bool Is_frieght { get; set; }
        public bool Is_hsn { get; set; }
        public bool Is_discount { get; set; }
        public bool Is_terms_conditions { get; set; }
        public bool Is_round { get; set; }
        public bool Is_customer_gstin { get; set; }
        public bool Is_customer_aadhar { get; set; }
        public bool Is_customer_pan { get; set; }
        public bool Is_company_logo { get; set; }
        public bool Is_company_gst { get; set; }
        public bool Is_company_phone { get; set; }
        public bool Is_company_email { get; set; }
        public bool Is_company_address { get; set; }
    }
}
