//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Svam.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_schememaster
    {
        public int ID { get; set; }
        public string SchemeNo { get; set; }
        public string SchemeName { get; set; }
        public string PrintName { get; set; }
        public string OnSale { get; set; }
        public string ItemSKU { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string Party { get; set; }
        public string Scheme { get; set; }
        public string Item { get; set; }
        public string Basis { get; set; }
        public string Ratio { get; set; }
        public string FromQty { get; set; }
        public string ToQty { get; set; }
        public string NewPrice { get; set; }
        public string Qty { get; set; }
        public string Discount { get; set; }
        public string FreeQty { get; set; }
        public string FreeItem { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> CompanyID { get; set; }
        public Nullable<int> BranchCode { get; set; }
        public string SyncID { get; set; }
        public Nullable<int> groupId { get; set; }
        public string flag { get; set; }
        public string Priority { get; set; }
        public string CustomerId { get; set; }
        public Nullable<int> IsMultyPrice { get; set; }
        public Nullable<double> MultyPrice { get; set; }
        public Nullable<double> MultyDiscount { get; set; }
    }
}
