//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Svam.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_tagcategory
    {
        public int id { get; set; }
        public string itemId { get; set; }
        public string sku { get; set; }
        public string categoryId { get; set; }
        public string subCategoryId { get; set; }
        public string subSubCategoryId { get; set; }
        public string brandId { get; set; }
        public string CompanyID { get; set; }
        public string BranchCode { get; set; }
        public string createdBy { get; set; }
        public string createdDate { get; set; }
        public string modifiedBy { get; set; }
        public Nullable<System.DateTime> modifiedDate { get; set; }
        public string SyncID { get; set; }
        public string flag { get; set; }
    }
}
