//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Svam.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_headings
    {
        public int Id { get; set; }
        public string Heading_1 { get; set; }
        public string Heading_2 { get; set; }
        public string Heading_3 { get; set; }
        public string Heading_4 { get; set; }
        public string CompanyId { get; set; }
        public string BranchCode { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedDate { get; set; }
        public string Flag { get; set; }
        public string SyncId { get; set; }
    }
}
