//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Svam.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_fatmawalines
    {
        public int Id { get; set; }
        public string VoucherNo { get; set; }
        public Nullable<System.DateTime> VoucherDate { get; set; }
        public string ItemName { get; set; }
        public string SKU { get; set; }
        public string Fat { get; set; }
        public string FatMrp { get; set; }
        public string CurrentQty { get; set; }
        public Nullable<decimal> PurchaseQty { get; set; }
        public Nullable<decimal> CutQty { get; set; }
        public Nullable<decimal> ActualQty { get; set; }
        public Nullable<decimal> CutMawa { get; set; }
        public string CreatedBy { get; set; }
        public string CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public string ModifiedDate { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public Nullable<int> BranchCode { get; set; }
        public string Flag { get; set; }
        public string SyncID { get; set; }
    }
}
