//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Svam.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_saleorder
    {
        public int ID { get; set; }
        public string BillNo { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public string Customer_Name { get; set; }
        public string MobileNo { get; set; }
        public string Address { get; set; }
        public string ItemName { get; set; }
        public string Unit { get; set; }
        public string Color { get; set; }
        public string Size { get; set; }
        public Nullable<int> Qty { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string PaymentMode { get; set; }
        public string RefNo { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<decimal> TotalQty { get; set; }
        public Nullable<decimal> TotalAmt { get; set; }
        public Nullable<decimal> ExtraDis { get; set; }
        public Nullable<decimal> Total { get; set; }
        public Nullable<decimal> Dis { get; set; }
        public string SaleRefNo { get; set; }
        public Nullable<decimal> Freight { get; set; }
        public Nullable<decimal> Recivable { get; set; }
        public Nullable<decimal> Recieved { get; set; }
        public Nullable<decimal> Gsttotal { get; set; }
        public Nullable<decimal> BalanceAmt { get; set; }
        public Nullable<decimal> Refund { get; set; }
        public Nullable<decimal> GrandTotal { get; set; }
        public string Shift { get; set; }
        public string Transport { get; set; }
        public string Remarks { get; set; }
        public Nullable<System.DateTime> Delivery { get; set; }
        public string Notes { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> Createddate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string tbl_saleordercol { get; set; }
        public string CompanyID { get; set; }
        public Nullable<int> Branch { get; set; }
        public string flag { get; set; }
        public string SyncID { get; set; }
        public string Customer_ID { get; set; }
        public string SystemVoucherNo { get; set; }
        public string EntryType { get; set; }
        public string sales_bill_type { get; set; }
        public string bill_type { get; set; }
        public string sales_order_status { get; set; }
        public string dtp_person { get; set; }
        public string binding_person { get; set; }
        public string printing_person { get; set; }
        public string printing_type { get; set; }
        public string colour { get; set; }
        public string proof_date { get; set; }
        public Nullable<int> status { get; set; }
        public string mode_dispatch { get; set; }
        public Nullable<decimal> packing_charges { get; set; }
        public Nullable<decimal> packing_charges_gst_per { get; set; }
        public Nullable<decimal> insurance_charges { get; set; }
        public Nullable<decimal> insurance_charges_gst_per { get; set; }
        public Nullable<decimal> forwarding_charges { get; set; }
        public Nullable<decimal> forwarding_charges_gst_per { get; set; }
        public Nullable<decimal> other_charges { get; set; }
        public Nullable<decimal> other_charges_gst_per { get; set; }
        public Nullable<decimal> freight_charges_gst_per { get; set; }
        public string OrderType { get; set; }
    }
}
