//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Svam.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblcustomertransportdetail
    {
        public int ct_id { get; set; }
        public string billno { get; set; }
        public string cust_id { get; set; }
        public string t_transID { get; set; }
        public string grrno { get; set; }
        public string vechileno { get; set; }
        public string station_place { get; set; }
        public Nullable<System.DateTime> t_date { get; set; }
        public string pin_no { get; set; }
        public string eway_req { get; set; }
        public Nullable<decimal> distance { get; set; }
        public string t_mode { get; set; }
        public string e_way_no { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string CompanyID { get; set; }
        public string BranchCode { get; set; }
        public string flag { get; set; }
        public string column1 { get; set; }
        public string column2 { get; set; }
        public Nullable<decimal> column3 { get; set; }
        public Nullable<decimal> column4 { get; set; }
        public string SyncID { get; set; }
    }
}
