//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Svam.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblprodecdemo
    {
        public int keyid { get; set; }
        public int pro_sub_id { get; set; }
        public string producykey { get; set; }
        public string pro_sub_code { get; set; }
        public Nullable<System.DateTime> createddate { get; set; }
        public Nullable<System.DateTime> modeifieddate { get; set; }
        public string createdby { get; set; }
        public string SyncID { get; set; }
        public string flag { get; set; }
    }
}
