//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Svam.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblsettingdetail
    {
        public int id { get; set; }
        public string server1 { get; set; }
        public string server1_slave { get; set; }
        public string server2 { get; set; }
        public string server2_slave { get; set; }
        public string column1 { get; set; }
        public string column2 { get; set; }
        public string column3 { get; set; }
        public string column4 { get; set; }
        public string SyncID { get; set; }
        public string flag { get; set; }
    }
}
