//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Svam.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblserialno
    {
        public int id { get; set; }
        public string sku { get; set; }
        public string voucherno { get; set; }
        public string serialno1 { get; set; }
        public string serialno2 { get; set; }
        public string serialno3 { get; set; }
        public string serialno4 { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string isuse { get; set; }
        public string BranchCode { get; set; }
        public string CompanyId { get; set; }
        public string ChalanNo { get; set; }
        public string IColour { get; set; }
        public string ISize { get; set; }
        public string flag { get; set; }
        public string SyncID { get; set; }
    }
}
