//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Svam.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbltransporter
    {
        public int tid { get; set; }
        public string t_transID { get; set; }
        public string t_name { get; set; }
        public string t_gstin { get; set; }
        public string t_address { get; set; }
        public string t_place { get; set; }
        public string t_pin { get; set; }
        public string t_state { get; set; }
        public string t_mobile { get; set; }
        public string t_emailid { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public string BranchCode { get; set; }
        public string CompanyId { get; set; }
        public string flag { get; set; }
        public string SyncID { get; set; }
    }
}
