//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Svam.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class temp_companyorders
    {
        public int ID { get; set; }
        public string ItemName { get; set; }
        public string ItemSKU { get; set; }
        public string itemid { get; set; }
        public int Quantity { get; set; }
        public float Amount { get; set; }
        public int CompanyID { get; set; }
        public int BranchID { get; set; }
        public int UserID { get; set; }
        public string IPAddress { get; set; }
        public Nullable<float> PurchasePrice { get; set; }
        public Nullable<float> MRP { get; set; }
        public string SyncID { get; set; }
        public string flag { get; set; }
        public string thumbnail_image { get; set; }
        public string InvNO { get; set; }
        public string details { get; set; }
    }
}
