//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Svam.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class time_zone
    {
        public int id { get; set; }
        public string country_code { get; set; }
        public string zone_name { get; set; }
        public string SyncId { get; set; }
        public string Flag { get; set; }
        public string standard_zone_name { get; set; }
    }
}
