//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Svam.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class transaction_details
    {
        public int id { get; set; }
        public string trans_id { get; set; }
        public string order_id { get; set; }
        public double amount { get; set; }
        public string trans_status { get; set; }
        public string company_id { get; set; }
        public string branch { get; set; }
        public string cust_id { get; set; }
        public System.DateTime created { get; set; }
    }
}
