//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Svam.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class wallet
    {
        public int id { get; set; }
        public string wallet_points { get; set; }
        public string refrel_code { get; set; }
        public string CompanyID { get; set; }
        public string branch { get; set; }
        public string user_id { get; set; }
        public string accept_user { get; set; }
        public int status { get; set; }
        public string created { get; set; }
        public string flag { get; set; }
        public string SyncID { get; set; }
        public string transaction_for { get; set; }
        public string for_id { get; set; }
        public string transaction_type { get; set; }
        public int transaction_amt { get; set; }
        public Nullable<int> BranchCode { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    }
}
