//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Svam.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class website_statistics
    {
        public int id { get; set; }
        public string name { get; set; }
        public string image { get; set; }
        public string description { get; set; }
        public string company_id { get; set; }
        public string branch_id { get; set; }
        public string status { get; set; }
        public string created_by { get; set; }
        public string created_at { get; set; }
        public string updated_by { get; set; }
        public System.DateTime updated_at { get; set; }
        public string syncId { get; set; }
        public string flag { get; set; }
    }
}
