//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Svam.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class whatsapp_setting
    {
        public int id { get; set; }
        public string api_key { get; set; }
        public string Password { get; set; }
        public string SenderID { get; set; }
        public string CompanyID { get; set; }
        public string BranchCode { get; set; }
        public string CreatedBy { get; set; }
        public string CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public string ModifiedDate { get; set; }
        public string mobile_no { get; set; }
        public string flag { get; set; }
        public string SyncID { get; set; }
    }
}
